SELECT 
    estacion,
    bloque,
    pasillo,
    posicion,
    IF(pmr = 1, 1, 0) AS pmr,
    IF(doble = 1, 1, 0) AS doble,
    estado_validadora,
    estado_torniquete,
    contador_in,
    contador_out,
    contador_validaciones,
    fh AS fecha_hora_eq_term,
    validadora_id,
    info_adicional,
    comando,
    fh_comando,
    tipo_pasillo_id,
    Id_estado_pasillo,
    codigo_pasillo,
    IF(piso_techo = 1, 1, 0) AS piso_techo,
    IF(motorizado = 1, 1, 0) AS motorizado,
    IF(invertido = 1, 1, 0) AS invertido
FROM estaciones;
