
/********************con proveedor*********************************/
SELECT DISTINCT a.ide_comov, b.ide_codem, a.mov_fecha_comov, a.tipo_movimiento, b.RUC, b.PROVEEDOR, a.detalle_comov, a.nro_comprobante_comov, b.cue_codigo_cocac, b.cue_descripcion_cocac,a.asiento_tipo, b.debe_codem, b.haber_codem,  SUM(COALESCE(b.debe_codem, 0)::numeric - COALESCE(b.haber_codem, 0)::numeric) AS saldo, a.detalle_gemes, b.fecha_ejecucion_prmen, b.devengado_prmen, b.cobrado_prmen, b.pagado_prmen,
( SELECT  tes_tipo_concepto1.detalle_tetic FROM tes_tipo_concepto tes_tipo_concepto1 WHERE tes_tipo_concepto1.ide_tetic = b.ide_tetic ) as centro_de_costo,
 a.estado 
FROM view_subconsult_tbl_a a 
LEFT JOIN view_subconsulta_tbl_b b ON a.ide_comov = b.ide_comov 
where mov_fecha_comov between '2025-01-01' and '2025-08-06' AND b.ide_cocac IN (SELECT ide_cocac FROM cont_catalogo_cuenta WHERE cue_codigo_cocac = '921.17.01.04') AND b.ruc IN ('1102768692001') GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21 ORDER BY b.cue_codigo_cocac 


/******************sin proveedor***********************/
select distinct ide_comov,ide_codem,mov_fecha_comov,tipo_movimiento, ruc, proveedor ,detalle_comov, nro_comprobante_comov, cue_codigo_cocac,cue_descripcion_cocac, asiento_tipo, COALESCE(debe_codem, 0)::numeric as debe_codem, COALESCE (haber_codem, 0)::numeric as haber_codem,  SUM(COALESCE(debe_codem, 0)::numeric - COALESCE (haber_codem, 0)::numeric)  AS saldo,  detalle_gemes,fecha_ejecucion_prmen,devengado_prmen,cobrado_prmen,pagado_prmen,estado  from ( select a.ide_comov,b.ide_codem,mov_fecha_comov,RUC,PROVEEDOR,tipo_movimiento,detalle_comov,asiento_tipo,nro_comprobante_comov, cue_codigo_cocac,cue_descripcion_cocac,debe_codem,haber_codem,detalle_gemes,fecha_ejecucion_prmen,devengado_prmen,cobrado_prmen,pagado_prmen,estado from ( 	 select ide_comov,mov_fecha_comov,detalle_comov,detalle_cotim as tipo_movimiento,detalle_conac as asiento_tipo,nro_comprobante_comov,detalle_gemes, 	 (case when activo_comov = false then 'NO MAYORIZADO' else 'MAYORIZADO' end) as estado 	 FROM cont_movimiento a   left join gen_mes b on b.ide_gemes = a.ide_gemes   left join cont_tipo_movimiento tm on tm.ide_cotim=a.ide_cotim   left join cont_nombre_asiento_contable nac on nac.ide_conac=a.ide_conac  ) a left join ( select coalesce(pro_det_mov.nombre_tepro, x.nombre_tepro, m.razon_social_recli) as PROVEEDOR, coalesce(pro_det_mov.ruc_tepro, x.ruc_tepro, m.ruc_comercial_recli) as RUC, a.ide_comov,a.ide_codem,debe_codem,haber_codem,cue_codigo_cocac,cue_descripcion_cocac,b.ide_cocac  	 ,fecha_ejecucion_prmen,devengado_prmen,cobrado_prmen,pagado_prmen 	 from cont_detalle_movimiento a  	 left join cont_catalogo_cuenta b on b.ide_cocac = a.ide_cocac   left join tes_proveedor pro_det_mov on pro_det_mov.ide_tepro = a.ide_tepro   left join cont_movimiento y on a.ide_comov=y.ide_comov      left join tes_comprobante_pago z on y.ide_tecpo=z.ide_tecpo     left join tes_proveedor x on z.ide_tepro=x.ide_tepro   left join cont_factura_asiento n on y.ide_comov=n.ide_comov   left join fac_factura l on n.ide_fafac=l.ide_fafac  left join rec_clientes m on l.ide_recli=m.ide_recli  	 left join (select ide_codem,fecha_ejecucion_prmen,sum(coalesce(devengado_prmen,0)) as devengado_prmen 	   ,sum(coalesce(cobrado_prmen,0)) as cobrado_prmen,sum(coalesce(pagado_prmen,0)) as pagado_prmen 	   from pre_mensual m  left join pre_anual a on a.ide_pranu=m.ide_pranu where ide_codem is not null  group by ide_codem,fecha_ejecucion_prmen) ejc on ejc.ide_codem=a.ide_codem ) b on a.ide_comov = b.ide_comov where mov_fecha_comov between '2025-01-01' and '2025-08-06' and ide_cocac IN (SELECT ide_cocac FROM cont_catalogo_cuenta WHERE cue_codigo_cocac = '921.17.01.16') AND ruc ISNULL   order by cue_codigo_cocac,mov_fecha_comov,nro_comprobante_comov  ) mayor  GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20 ORDER BY cue_codigo_cocac 