SELECT 
CASE WHEN prison_move."type" = 'internal' THEN
		 'INTERNO'
		 WHEN prison_move."type" = 'in' THEN
		 'INGRESO'
		 WHEN prison_move."type" = 'free' THEN
		'LIBRE'
	ELSE
		'EXTERNO'
END AS "TIPO DE TRASLADO", prison_person.identificador AS "IDENTIFICADOR",prison_person.name AS "NOMBRES DEL PLL", prison_person.last_name as "APELLIDOS DEL PPL", prison_move."date" "FECHA DE TRASLADO", 

(SELECT complete_name from prison_location pl3 WHERE pl3.id=prison_move.loc_from_id) AS "TRASLADO ORIGEN" ,
(SELECT complete_name from prison_location pl5 WHERE pl5.id=prison_move.location_id) AS "TRASLADO DESTINO",
( SELECT prison_location_1.name  FROM prison_location prison_location_1 WHERE (prison_location_1.id = prison_person.etapa_id)) AS "ETAPA ACTUAL",
    ( SELECT prison_location_1.name FROM prison_location prison_location_1 WHERE (prison_location_1.id = prison_person.pabellon_id)) AS "PABELLON ACTUAL",
    ( SELECT prison_location_1.name FROM prison_location prison_location_1 WHERE (prison_location_1.id = prison_person.ala_id)) AS "ALA ACTUAL",
    ( SELECT prison_location_1.name FROM prison_location prison_location_1 WHERE (prison_location_1.id = prison_person.piso_id)) AS "PISO ACTUAL",
res_partner.name as "REALIZADO POR",res_users."login" as "USUARIO AD",
CASE
       WHEN prison_move.obser_traslado = '0' THEN 'INGRESO INICIAL'
			 WHEN prison_move.obser_traslado = '1' THEN 'SANCION DISCIPLINARIA'
			 WHEN prison_move.obser_traslado = '2' THEN 'DISPOSICION MINISTERIAL'
			 WHEN prison_move.obser_traslado = '3' THEN 'PROGRESION'
			 WHEN prison_move.obser_traslado = '4' THEN 'REGRESION'
			 WHEN prison_move.obser_traslado = '5' THEN 'ENFERMEDAD'
			 WHEN prison_move.obser_traslado = '6' THEN 'SEGURIDAD'
	     ELSE 'SIN OBSERVACION'
END as "OBSEVACIONES"
 FROM prison_person 
 INNER JOIN person_fiscalia_prontuario on prison_person.prontuario= person_fiscalia_prontuario.prontuario
 INNER JOIN prison_location    on prison_person.center_id = prison_location.id 
 INNER JOIN prison_move        on prison_person.id        = prison_move.ppl_id
 inner JOIN res_users          on prison_move.write_uid   = res_users.id
 INNER JOIN res_partner        on res_users.partner_id    = res_partner."id"
 WHERE prison_move."date" BETWEEN  '2020-06-01' AND '2020-11-01' 
 AND   prison_move."type"='internal' ORDER BY 4  
 /*AND (prison_person.last_name ILIKE '%ALMEIDA QUIZHPI%' OR prison_person."name" ILIKE '%LENIN ALEXIS%' )
OR (prison_person.last_name ILIKE '%MANTILLA AVILA%' OR prison_person."name" ILIKE '%SEGUNDO HUMBERTO%' )
OR (prison_person.last_name ILIKE '%VASCO ALLAUCA%' OR prison_person."name" ILIKE '%FRANKLIN STALIN%' )
OR (prison_person.last_name ILIKE '%CADENA SIMBAÑA%' OR prison_person."name" ILIKE '%HERNAN PATRICIO%' )
OR (prison_person.last_name ILIKE '%ESPINOZA CHARIGUAMAN%' OR prison_person."name" ILIKE '%GUIDO ROMAN%' )
OR (prison_person.last_name ILIKE '%LEON BARAHONA%' OR prison_person."name" ILIKE '%MARCO FRANCISCO%' )
OR (prison_person.last_name ILIKE '%MACIAS CADENA%' OR prison_person."name" ILIKE '%GABRIEL ALEJANDRO%' )
OR (prison_person.last_name ILIKE '%PARRALES VERA%' OR prison_person."name" ILIKE '%IGNACIO LEONIDAS%' )
OR (prison_person.last_name ILIKE '%PROAÑO PINO%' OR prison_person."name" ILIKE '%ALEX MAURICIO%' )
OR (prison_person.last_name ILIKE '%SIGUENZA ARMIJOS%' OR prison_person."name" ILIKE '%VICENTE RENE%' )
OR (prison_person.last_name ILIKE '%UBIDIA GONZALEZ%' OR prison_person."name" ILIKE '%EDGAR GEOVANNY%' )
OR (prison_person.last_name ILIKE '%VERA AMPUERO%' OR prison_person."name" ILIKE '%LUIS FELIPE%' )
OR (prison_person.last_name ILIKE '%VERGARA BARREIROS%' OR prison_person."name" ILIKE '%DAVID ISAIA%' )
OR (prison_person.last_name ILIKE '%VILLAREAL MUÑOZ%' OR prison_person."name" ILIKE '%LUIS FERNANDO%' )
OR (prison_person.last_name ILIKE '%ORTEGA ALVAREZ%' OR prison_person."name" ILIKE '%VICTOR ALFONSO%' )
OR (prison_person.last_name ILIKE '%TOCTE CHUSIN%' OR prison_person."name" ILIKE '%FRANKLIN FREDDY%' )
OR (prison_person.last_name ILIKE '%GARCIA VENEGAS%' OR prison_person."name" ILIKE '%BOLIVAR GERARDO%' )
OR (prison_person.last_name ILIKE '%ALVAREZ QUINTERO%' OR prison_person."name" ILIKE '%VICTOR JULIO%' )
OR (prison_person.last_name ILIKE '%BARRE BONE%' OR prison_person."name" ILIKE '%DARWIN JAVIER%' )
OR (prison_person.last_name ILIKE '%RENTERIA FRANCO%' OR prison_person."name" ILIKE '%FREDDY STEVEN%' )
OR (prison_person.last_name ILIKE '%PALACIOS AYOVI%' OR prison_person."name" ILIKE '%LUIS CESAR%' )
OR (prison_person.last_name ILIKE '%COLLANTES ALIAGA%' OR prison_person."name" ILIKE '%GUIDO EDEN%' )
OR (prison_person.last_name ILIKE '%ZAMBRANO CHACON%' OR prison_person."name" ILIKE '%CRISTHIAN RAFAEL%' )
OR (prison_person.last_name ILIKE '%FARINANGO QUITO%' OR prison_person."name" ILIKE '%ELVIS ADRIAN%' )
OR (prison_person.last_name ILIKE '%MOLINA CAHUASQUI%' OR prison_person."name" ILIKE '%FERNANDO PATRICIO%' )
OR (prison_person.last_name ILIKE '%ROSADO ZAMBRANO%' OR prison_person."name" ILIKE '%JUAN CARLOS%' )
OR (prison_person.last_name ILIKE '%CAIZA TOCAGON%' OR prison_person."name" ILIKE '%JOSE%' )
OR (prison_person.last_name ILIKE '%DIAZ MAÑONERO%' OR prison_person."name" ILIKE '%JESUS EVELIO%' )
OR (prison_person.last_name ILIKE '%ESTUPIÑAN ANGULO%' OR prison_person."name" ILIKE '%HUGO%' )
OR (prison_person.last_name ILIKE '%RUALES TUZA%' OR prison_person."name" ILIKE '%DIEGO DAVID%' )
OR (prison_person.last_name ILIKE '%GONZALEZ ALEGRIA%' OR prison_person."name" ILIKE '%ALDO RUFINO%' )
OR (prison_person.last_name ILIKE '%BENAVIDES JACOME%' OR prison_person."name" ILIKE '%LUIS EDUARDO%' )
OR (prison_person.last_name ILIKE '%CEDEÑO VEINTIMILLLA%' OR prison_person."name" ILIKE '%JAIRO JAVIER%' )
OR (prison_person.last_name ILIKE '%CIFUENTES BETANCOURT%' OR prison_person."name" ILIKE '%JUAN PABLO%' )
OR (prison_person.last_name ILIKE '%CONTRERAS MORA%' OR prison_person."name" ILIKE '%ROBIN JESUS%' )
OR (prison_person.last_name ILIKE '%GARCIA PALMA%' OR prison_person."name" ILIKE '%JESUS EMANUEL%' )
OR (prison_person.last_name ILIKE '%HERAS LUNA%' OR prison_person."name" ILIKE '%WILMAN RENE%' )
OR (prison_person.last_name ILIKE '%LASSO VILLAVICENCIO%' OR prison_person."name" ILIKE '%RICARDO MARCELO%' )
OR (prison_person.last_name ILIKE '%PARRAGA%' OR prison_person."name" ILIKE '%PEDRO PABLO%' )
OR (prison_person.last_name ILIKE '%RAMIREZ CEVALLOS%' OR prison_person."name" ILIKE '%EDGAR HUMBERTO%' )
OR (prison_person.last_name ILIKE '%SALAZAR ALVARADO%' OR prison_person."name" ILIKE '%ORLANDO JOSE%' )
OR (prison_person.last_name ILIKE '%SOLIS MARTINEZ%' OR prison_person."name" ILIKE '%JOHNNY JAVIER%' )
OR (prison_person.last_name ILIKE '%VALVERDE LANDAZURI%' OR prison_person."name" ILIKE '%JHON ALEXANDER%' )
OR (prison_person.last_name ILIKE '%ZAMBRANO LOOR%' OR prison_person."name" ILIKE '%BOLIVAR AGUSTIN%' )
OR (prison_person.last_name ILIKE '%ZAMBRANO MOLINA%' OR prison_person."name" ILIKE '%ORLY MAURICIO%' )
OR (prison_person.last_name ILIKE '%YUPANQUI CAILLATASIG%' OR prison_person."name" ILIKE '%JONATHAN MARCELO%' )
OR (prison_person.last_name ILIKE '%VENEGAS MIRANDA%' OR prison_person."name" ILIKE '%JULIO SANTIAGO%' )
OR (prison_person.last_name ILIKE '%CHIMBORAZO COCHA%' OR prison_person."name" ILIKE '%LUIS ALBERTO%' )
OR (prison_person.last_name ILIKE '%MONTENEGRO RAMIREZ%' OR prison_person."name" ILIKE '%JHON EDISON%' )
OR (prison_person.last_name ILIKE '%QUILUMBAQUIN TOAPANTA%' OR prison_person."name" ILIKE '%RAUL GUSTAVO%' )
OR (prison_person.last_name ILIKE '%GORDILLO DUARTE%' OR prison_person."name" ILIKE '%CLEVER ORLANDO%' )
OR (prison_person.last_name ILIKE '%MACIAS ESPIN%' OR prison_person."name" ILIKE '%LUOIS ARTURO%' )
OR (prison_person.last_name ILIKE '%CARANQUI MISHQUI%' OR prison_person."name" ILIKE '%ALEXANDER PATRICIO%' )
OR (prison_person.last_name ILIKE '%GUALSAQUI QUILUMBA%' OR prison_person."name" ILIKE '%JOSE MARIA%' )
OR (prison_person.last_name ILIKE '%SALAZAR VILLACIS%' OR prison_person."name" ILIKE '%HUGO MARCONI%' )
OR (prison_person.last_name ILIKE '%SOPA CHANCHICOCHA%' OR prison_person."name" ILIKE '%CRISTIAN IVAN%' )
OR (prison_person.last_name ILIKE '%RIASCOS LOPEZ%' OR prison_person."name" ILIKE '%HENRY FERNEY%' )
OR (prison_person.last_name ILIKE '%PUENAYAN CHAPI%' OR prison_person."name" ILIKE '%JAIME ARMANDO%' )
OR (prison_person.last_name ILIKE '%POLO CRUZ%' OR prison_person."name" ILIKE '%ROBYN JAVIER%' )
OR (prison_person.last_name ILIKE '%CUEVA CALDERON%' OR prison_person."name" ILIKE '%CARLOS ANDRES%' )
OR (prison_person.last_name ILIKE '%TAIPE DE LA CRUZ%' OR prison_person."name" ILIKE '%EDISON PATRICIO%' )
OR (prison_person.last_name ILIKE '%SALTOS MOREIRA%' OR prison_person."name" ILIKE '%PETER ALIPIO%' )
OR (prison_person.last_name ILIKE '%CALERO MUÑOZ%' OR prison_person."name" ILIKE '%HUGO ANDRES%' )
OR (prison_person.last_name ILIKE '%CHIPANTASIG TENENUELA%' OR prison_person."name" ILIKE '%CARLOS PATRICIO%' )
OR (prison_person.last_name ILIKE '%ROJAS CUELLAR%' OR prison_person."name" ILIKE '%HERNANDO%' )
OR (prison_person.last_name ILIKE '%HERRERIA RODRIGUEZ%' OR prison_person."name" ILIKE '%EDISON ALFREDO%' )
OR (prison_person.last_name ILIKE '%MORENO SALAO%' OR prison_person."name" ILIKE '%DAVID WILFRIDO%' )
OR (prison_person.last_name ILIKE '%PINARGOTE CUSME%' OR prison_person."name" ILIKE '%ALEXIS GREGORIO%' )
OR (prison_person.last_name ILIKE '%LUNA RUANO%' OR prison_person."name" ILIKE '%JHON MAURICIO%' )
OR (prison_person.last_name ILIKE '%MALAGON BUSTOS%' OR prison_person."name" ILIKE '%GERSON DAVID%' )
OR (prison_person.last_name ILIKE '%QUIÑONES CABEZAS%' OR prison_person."name" ILIKE '%JHON JUAN%' )
OR (prison_person.last_name ILIKE '%CHAVEZ CASTILLO%' OR prison_person."name" ILIKE '%JUAN CARLOS%' )
OR (prison_person.last_name ILIKE '%GARZON BUITRAGO%' OR prison_person."name" ILIKE '%JAVIER%' )
OR (prison_person.last_name ILIKE '%CHICA OSORIO%' OR prison_person."name" ILIKE '%ABIMELEC%' )
OR (prison_person.last_name ILIKE '%ESTUPIÑAN RANGEL%' OR prison_person."name" ILIKE '%FREDDY ALFREDO%' )
OR (prison_person.last_name ILIKE '%CEVALLOS CONFORME %' OR prison_person."name" ILIKE '%JOFFRE ALBERTO%' )
OR (prison_person.last_name ILIKE '%BENAVIDES ENRIQUEZ%' OR prison_person."name" ILIKE '%JONATHAN GERARDO%' )
OR (prison_person.last_name ILIKE '%CASTILLO MORENO%' OR prison_person."name" ILIKE '%RAUL%' )
OR (prison_person.last_name ILIKE '%CHILUISA ALMACHE%' OR prison_person."name" ILIKE '%ANGEL MARIA%' )
OR (prison_person.last_name ILIKE '%HERNANDEZ HERNANDEZ%' OR prison_person."name" ILIKE '%FREDDY%' )
OR (prison_person.last_name ILIKE '%PAILLIACHO ZAMORA%' OR prison_person."name" ILIKE '%EGUIVER ALEXANDER%' )
OR (prison_person.last_name ILIKE '%PALLO VEGA%' OR prison_person."name" ILIKE '%JUAN CESAR%' )
OR (prison_person.last_name ILIKE '%RAMON RAMON%' OR prison_person."name" ILIKE '%VINICIO RUBEN%' )
OR (prison_person.last_name ILIKE '%PINCAY PERALTA%' OR prison_person."name" ILIKE '%FAUSTINO EUGENIO%' )
OR (prison_person.last_name ILIKE '%CALCAN ULCUANGO%' OR prison_person."name" ILIKE '%SEGUNDO MANUEL%' )
OR (prison_person.last_name ILIKE '%ESPINOSA FLORES%' OR prison_person."name" ILIKE '%JOSE CARLOS%' )
OR (prison_person.last_name ILIKE '%MOLINA FARINANGO%' OR prison_person."name" ILIKE '%JOSE PASCUAL%' )
OR (prison_person.last_name ILIKE '%NAVAS MACIAS%' OR prison_person."name" ILIKE '%ROBERT FRANCISCO%' )
OR (prison_person.last_name ILIKE '%SANCHEZ CAHUASQUI%' OR prison_person."name" ILIKE '%JOSE ANTONIO%' )
OR (prison_person.last_name ILIKE '%TADEO MINAYA%' OR prison_person."name" ILIKE '%DANNY FABIAN%' )
OR (prison_person.last_name ILIKE '%VERA ZAMBRANO%' OR prison_person."name" ILIKE '%JIMMY ALFREDO%' )
OR (prison_person.last_name ILIKE '%YAPANGUI PILA%' OR prison_person."name" ILIKE '%LUIS SERGIO%' )
OR (prison_person.last_name ILIKE '%BAGUI CASTAÑEDA%' OR prison_person."name" ILIKE '%PELLECEY%' )
OR (prison_person.last_name ILIKE '%GUAMAN CANDO%' OR prison_person."name" ILIKE '%JAIME GILBERTO%' )
OR (prison_person.last_name ILIKE '%ROSALES GAVIDIA%' OR prison_person."name" ILIKE '%ANGEL RAMIRO%' )
OR (prison_person.last_name ILIKE '%HERRERA FLORES%' OR prison_person."name" ILIKE '%PEDRO YASMANI%' )
OR (prison_person.last_name ILIKE '%SANCHEZ LOPEZ%' OR prison_person."name" ILIKE '%ANGEL FORTUNATO%' )
OR (prison_person.last_name ILIKE '%FARIAS ESMERALDA%' OR prison_person."name" ILIKE '%CESAR AUGUSTO%' )
OR (prison_person.last_name ILIKE '%PHETER BALOY%' OR prison_person."name" ILIKE '%CRISTHIAN HUMBERTO%' )
OR (prison_person.last_name ILIKE '%PHETER BALOY%' OR prison_person."name" ILIKE '%ROMEL LEODAN%' )
OR (prison_person.last_name ILIKE '%SALAZAR SEVILLANO%' OR prison_person."name" ILIKE '%LUIS ALFONSO%' )
OR (prison_person.last_name ILIKE '%TIGUA QUIZMIZ%' OR prison_person."name" ILIKE '%ESTEBAN REY%' )
OR (prison_person.last_name ILIKE '%ALARCON QUIÑONEZ%' OR prison_person."name" ILIKE '%JOSE JUSTINO%' )
OR (prison_person.last_name ILIKE '%GARCIA MIRANDA%' OR prison_person."name" ILIKE '%LUIS MIGUEL%' )
OR (prison_person.last_name ILIKE '%BRAVO SELLAN%' OR prison_person."name" ILIKE '%DIEGO RAFAEL%' )
OR (prison_person.last_name ILIKE '%REQUELME BRAVO%' OR prison_person."name" ILIKE '%JOSE DAVID%' )
OR (prison_person.last_name ILIKE '%DIAZ VILLARRUEL%' OR prison_person."name" ILIKE '%NEIL JIMMY%' )
OR (prison_person.last_name ILIKE '%HERMOSA YELA%' OR prison_person."name" ILIKE '%BERDIEL AUDELO%' )
OR (prison_person.last_name ILIKE '%SOLORZANO MACIAS%' OR prison_person."name" ILIKE '%MANUEL BENJAMIN%' )
OR (prison_person.last_name ILIKE '%IMBAQUINGO GARCIA%' OR prison_person."name" ILIKE '%JOSE ELIAS%' )
OR (prison_person.last_name ILIKE '%ESCOBAR IPIALES %' OR prison_person."name" ILIKE '%DAVID STEVEN%' )
OR (prison_person.last_name ILIKE '%ARMIJOS BONILLA%' OR prison_person."name" ILIKE '%JOSE RAMIRO%' )
OR (prison_person.last_name ILIKE '%CANCHIMBRE QUIÑONEZ%' OR prison_person."name" ILIKE '%MANUEL ENRIQUE%' )
OR (prison_person.last_name ILIKE '%CHARLAR ESPINOZA %' OR prison_person."name" ILIKE '%JOSE ALBERTO%' )
OR (prison_person.last_name ILIKE '%ESTUPIÑAN MEDINA%' OR prison_person."name" ILIKE '%MARIO FABRICIO%' )
OR (prison_person.last_name ILIKE '%GARCIA ENRIQUEZ%' OR prison_person."name" ILIKE '%KELVIN DANIEL%' )
OR (prison_person.last_name ILIKE '%GARCIA ORTEGA %' OR prison_person."name" ILIKE '%ROBERTO CARLOS%' )
OR (prison_person.last_name ILIKE '%VELEZ AGUIRRE %' OR prison_person."name" ILIKE '%MANUEL ALBERTO%' )
OR (prison_person.last_name ILIKE '%BURBANO VILLACIS %' OR prison_person."name" ILIKE '%ANDRES JAVIER%' )
OR (prison_person.last_name ILIKE '%RUALES PIJAL%' OR prison_person."name" ILIKE '%SEGUNDO ANTONIO%' )
OR (prison_person.last_name ILIKE '%CABASCANGO CUTI%' OR prison_person."name" ILIKE '%OSCAR DANIEL%' )
OR (prison_person.last_name ILIKE '%CAÑAR RUALES%' OR prison_person."name" ILIKE '%JUAN GABRIEL%' )
OR (prison_person.last_name ILIKE '%JIMENEZ ARGOTI%' OR prison_person."name" ILIKE '%LUIS HUMBERTO%' )
OR (prison_person.last_name ILIKE '%JAEN MEZA%' OR prison_person."name" ILIKE '%ANGEL SIMON%' )
OR (prison_person.last_name ILIKE '%CASTRO CORTEZ%' OR prison_person."name" ILIKE '%NIXON FRANCISCO%' )
OR (prison_person.last_name ILIKE '%CUPUERAN PUPIALES%' OR prison_person."name" ILIKE '%JORGE ALBERTO%' )
OR (prison_person.last_name ILIKE '%PACAS UQUILLAS%' OR prison_person."name" ILIKE '%JOSE DAVID%' )
OR (prison_person.last_name ILIKE '%MOTA REINOSO%' OR prison_person."name" ILIKE '%CARLOS ANDRES%' )
OR (prison_person.last_name ILIKE '%NEUMANN VITERI%' OR prison_person."name" ILIKE '%JULIAN ANDRES%' )
OR (prison_person.last_name ILIKE '%MONTALVO YEPEZ%' OR prison_person."name" ILIKE '%JAIME ORLANDO%' )
OR (prison_person.last_name ILIKE '%LEGÑA LIGNIA%' OR prison_person."name" ILIKE '%JESUS ENRIQUE%' )
OR (prison_person.last_name ILIKE '%ASIMBAYA ROJAS %' OR prison_person."name" ILIKE '%ANGEL MIGUEL%' )
OR (prison_person.last_name ILIKE '%YANEZ SANTO%' OR prison_person."name" ILIKE '%OSCAR MAURICIO%' )
OR (prison_person.last_name ILIKE '%VASCONEZ PALLO%' OR prison_person."name" ILIKE '%HENRRY RAMIRO%' )
OR (prison_person.last_name ILIKE '%LEON JACOME%' OR prison_person."name" ILIKE '%JEFFERSON BOLIVAR%' )
OR (prison_person.last_name ILIKE '%SANTILLAN GABELA%' OR prison_person."name" ILIKE '%VICTOR ANDRES%' )
OR (prison_person.last_name ILIKE '%GUEVARA ZAMBRANO%' OR prison_person."name" ILIKE '%FRICKSON DUQUERMAN%' )
OR (prison_person.last_name ILIKE '%MASACHE PANEZO%' OR prison_person."name" ILIKE '%MARLON PATRICIO%' )
OR (prison_person.last_name ILIKE '%BONIFAZ RICO%' OR prison_person."name" ILIKE '%LUIS BAYARDO%' )
OR (prison_person.last_name ILIKE '%MINA CASTRO%' OR prison_person."name" ILIKE '%CHRISTIAN FERNANDO%' )
OR (prison_person.last_name ILIKE '%CANDELARIO PONCE %' OR prison_person."name" ILIKE '%VICTOR EDUARDO%' )
OR (prison_person.last_name ILIKE '%ENRIQUEZ TOBAR%' OR prison_person."name" ILIKE '%WALTER WILFRIDO%' )
OR (prison_person.last_name ILIKE '%LOACHAMIN LINCANGO%' OR prison_person."name" ILIKE '%JOSE MANUEL%' )
OR (prison_person.last_name ILIKE '%JAMA CANCHINGRE%' OR prison_person."name" ILIKE '%DARIO SIBARDI%' )
OR (prison_person.last_name ILIKE '%BRITO ORTIZ%' OR prison_person."name" ILIKE '%PABLO ALEJANDRO%' )
OR (prison_person.last_name ILIKE '%GREFA TANGUILA%' OR prison_person."name" ILIKE '%BYRON WILFRIDO%' )
OR (prison_person.last_name ILIKE '%KAJEKAI TSENKUSH%' OR prison_person."name" ILIKE '%LUIS ENGADY%' )
OR (prison_person.last_name ILIKE '%ARCE MENDEZ%' OR prison_person."name" ILIKE '%JHONATAN DAVID%' )
OR (prison_person.last_name ILIKE '%CONDOR CUASMAYAN%' OR prison_person."name" ILIKE '%MIGUEL ANGEL%' )
OR (prison_person.last_name ILIKE '%LITUMA PACHECO%' OR prison_person."name" ILIKE '%JONATHAN GUSTAVO%' )
OR (prison_person.last_name ILIKE '%MONTAÑO MANCILLA%' OR prison_person."name" ILIKE '%JHON ALEXANDER%' )
OR (prison_person.last_name ILIKE '%ZAMBRANO REASCO%' OR prison_person."name" ILIKE '%RONNY PATRICIO%' )
OR (prison_person.last_name ILIKE '%LAMAR ROCHA%' OR prison_person."name" ILIKE '%SEGUNDO CLEVER%' )
OR (prison_person.last_name ILIKE '%MALA BOLAÑOS%' OR prison_person."name" ILIKE '%ALFREDO JOSE%' )
OR (prison_person.last_name ILIKE '%MASABANDA REA%' OR prison_person."name" ILIKE '%EDWIN VINICIO%' )
OR (prison_person.last_name ILIKE '%MAZA AJILA%' OR prison_person."name" ILIKE '%FRANKLIN RAMIRO%' )
OR (prison_person.last_name ILIKE '%SALAMBAY CHISAGUANO%' OR prison_person."name" ILIKE '%LUIS EDUARDO%' )
OR (prison_person.last_name ILIKE '%INTRIAGO JARAMILLO%' OR prison_person."name" ILIKE '%JUNIOR SIGIFREDO%' )
OR (prison_person.last_name ILIKE '%PAZ CEDEÑO%' OR prison_person."name" ILIKE '%RICARDO DANIEL%' )
OR (prison_person.last_name ILIKE '%ASITUMBAY GAGLAY%' OR prison_person."name" ILIKE '%GONZALO WILLIAM%' )
OR (prison_person.last_name ILIKE '%SILVA DELGADO%' OR prison_person."name" ILIKE '%BRYAN ALEXANDER%' )
OR (prison_person.last_name ILIKE '%MONTENEGRO RON%' OR prison_person."name" ILIKE '%KEVIN GEOVANNY%' )
OR (prison_person.last_name ILIKE '%ROSERO DORADO%' OR prison_person."name" ILIKE '%FRANCO HENRRY%' )
OR (prison_person.last_name ILIKE '%TERMAL RIOFRIO%' OR prison_person."name" ILIKE '%LUIS ALBERTO%' )
OR (prison_person.last_name ILIKE '%CHICAIZA TIPAN%' OR prison_person."name" ILIKE '%DARWIN JAVIER%' )
OR (prison_person.last_name ILIKE '%GOMEZ CATUTO%' OR prison_person."name" ILIKE '%SANTIAGO EZEQUIEL%' )
OR (prison_person.last_name ILIKE '%MARQUEZ CABRERA%' OR prison_person."name" ILIKE '%MIGUEL GONZALO%' )
OR (prison_person.last_name ILIKE '%MARQUEZ MOLINA%' OR prison_person."name" ILIKE '%FAVIAN ESTALIN%' )
OR (prison_person.last_name ILIKE '%MIÑO IPAZ%' OR prison_person."name" ILIKE '%OSCAR HERMEL%' )
OR (prison_person.last_name ILIKE '%VELASQUEZ INTRIAGO%' OR prison_person."name" ILIKE '%ALFONSO SIGIFREDO%' )
OR (prison_person.last_name ILIKE '%DEFAZ TOAPANTA%' OR prison_person."name" ILIKE '%CARLOS RUBEN%' )
OR (prison_person.last_name ILIKE '%VINUEZA SALAZAR%' OR prison_person."name" ILIKE '%FRANKLIN GEOVANNY%' )
OR (prison_person.last_name ILIKE '%SANDOYA CONTRERAS%' OR prison_person."name" ILIKE '%JORGE CHRISTIAN%' )
OR (prison_person.last_name ILIKE '%GONZALEZ ANGULO%' OR prison_person."name" ILIKE '%VICTOR MANUEL%' )
OR (prison_person.last_name ILIKE '%ROJAS VERDEZOTO%' OR prison_person."name" ILIKE '%MIGUEL ANGEL%' )
OR (prison_person.last_name ILIKE '%PROAÑO QUISHPE%' OR prison_person."name" ILIKE '%ANGEL MARIA%' )
OR (prison_person.last_name ILIKE '%CARBO VILLAMAR%' OR prison_person."name" ILIKE '%GILBERTO OSWALDO%' )
OR (prison_person.last_name ILIKE '%APRAEZ DUQUE%' OR prison_person."name" ILIKE '%ANDRES DAVID%' )
OR (prison_person.last_name ILIKE '%AGUIRRE MARTINEZ%' OR prison_person."name" ILIKE '%NELSON ADRIAN%' )
OR (prison_person.last_name ILIKE '%BARRERA CHICAIZA%' OR prison_person."name" ILIKE '%JOSELITO %' )
OR (prison_person.last_name ILIKE '%RODRIGUEZ VALDEZ%' OR prison_person."name" ILIKE '%VICTOR HUGO%' )
OR (prison_person.last_name ILIKE '%MUENALA GUTIERREZ%' OR prison_person."name" ILIKE '%CARLOS ALBERTO%' )
OR (prison_person.last_name ILIKE '%ORTIZ CONTRERAS%' OR prison_person."name" ILIKE '%CHRISTIAN ROBERTO%' )
OR (prison_person.last_name ILIKE '%LEON PEDROZA%' OR prison_person."name" ILIKE '%EUCEPPEE %' )
OR (prison_person.last_name ILIKE '%RODRIGUEZ HERRERA%' OR prison_person."name" ILIKE '%DIEGO FERNANDO%' )
OR (prison_person.last_name ILIKE '%CHICAIZA CAIZA%' OR prison_person."name" ILIKE '%WALTER VINICIO%' )
OR (prison_person.last_name ILIKE '%YANGUICELA CEPEDA%' OR prison_person."name" ILIKE '%GUILLERMO RODRIGO%' )
OR (prison_person.last_name ILIKE '%SARAGOSIN GUALLICHICO%' OR prison_person."name" ILIKE '%JUAN CARLOS%' )
OR (prison_person.last_name ILIKE '%AVILEZ HUATATOCA%' OR prison_person."name" ILIKE '%WIDINSON JAVIER%' )
OR (prison_person.last_name ILIKE '%CABASCANGO FERNANDEZ%' OR prison_person."name" ILIKE '%LUIS ALFONSO%' )
OR (prison_person.last_name ILIKE '%MURCIA SANCHEZ%' OR prison_person."name" ILIKE '%LEONTE %' )
OR (prison_person.last_name ILIKE '%LOPEZ SOLIS%' OR prison_person."name" ILIKE '%JORGE CALIXTO%' )
OR (prison_person.last_name ILIKE '%CARRION GUACHAMBOZA%' OR prison_person."name" ILIKE '%VICTOR ALFONSO%' )
OR (prison_person.last_name ILIKE '%JACOME HIDALGO%' OR prison_person."name" ILIKE '%LUIS RICARDO%' )
OR (prison_person.last_name ILIKE '%OROZCO BURGOS%' OR prison_person."name" ILIKE '%RAFAEL ANISAL%' )
OR (prison_person.last_name ILIKE '%CHIMBO SASNALEMA%' OR prison_person."name" ILIKE '%LUIS MIGUEL%' )
OR (prison_person.last_name ILIKE '%MACIAS CASQUETE%' OR prison_person."name" ILIKE '%RAFAEL WALTER%' )
OR (prison_person.last_name ILIKE '%CASTRO GALARZA%' OR prison_person."name" ILIKE '%MARIO VICENTE%' )
OR (prison_person.last_name ILIKE '%DIAZ RUILOBA%' OR prison_person."name" ILIKE '%ANGEL CRISTIAN%' )
OR (prison_person.last_name ILIKE '%MEDINA BOLAÑO%' OR prison_person."name" ILIKE '%CARLOS EDUARDO%' )
OR (prison_person.last_name ILIKE '%SILVA PISUÑA%' OR prison_person."name" ILIKE '%HENRY FERNANDO%' )
OR (prison_person.last_name ILIKE '%VIGO CACERES%' OR prison_person."name" ILIKE '%CESAR AUGUSTO%' )
OR (prison_person.last_name ILIKE '%CARTAGENA CHUQUITARCO%' OR prison_person."name" ILIKE '%CARLOS ALBERTO%' )
OR (prison_person.last_name ILIKE '%POZO POVEA%' OR prison_person."name" ILIKE '%DENIS RICARDO%' )
OR (prison_person.last_name ILIKE '%MINA DIAS%' OR prison_person."name" ILIKE '%JUAN ANDRES%' )
OR (prison_person.last_name ILIKE '%ANGULO TORRES%' OR prison_person."name" ILIKE '%SILVIO JAVIER%' )
OR (prison_person.last_name ILIKE '%GARCIA DUMES%' OR prison_person."name" ILIKE '%WILSON ALFREDO%' )
OR (prison_person.last_name ILIKE '%NEGRETE GUEVARA%' OR prison_person."name" ILIKE '%JORGE WASHINGTON%' )
OR (prison_person.last_name ILIKE '%PUENTE PAZOS%' OR prison_person."name" ILIKE '%EDISON FERNANDO%' )
OR (prison_person.last_name ILIKE '%BOMBON SIMBA%' OR prison_person."name" ILIKE '%EDWIN MARCELO%' )
OR (prison_person.last_name ILIKE '%CAJAS VALENCIA %' OR prison_person."name" ILIKE '%ALFREDO JESÚS%' )
OR (prison_person.last_name ILIKE '%BONE PORTOCARRERO %' OR prison_person."name" ILIKE '%VICTOR MANUEL%' )
OR (prison_person.last_name ILIKE '%CARMENATE MADRIGAL %' OR prison_person."name" ILIKE '%JUAN GABRIEL%' )
OR (prison_person.last_name ILIKE '%CEDENO MENDOZA %' OR prison_person."name" ILIKE '%ITALO SALOMON%' )
OR (prison_person.last_name ILIKE '%CISNEROS VILLOTA %' OR prison_person."name" ILIKE '%FABER%' )
OR (prison_person.last_name ILIKE '%ESTACIO ANRANGO %' OR prison_person."name" ILIKE '%ALEX DARIO%' )
OR (prison_person.last_name ILIKE '%SALVADOR ECHEVERRIA %' OR prison_person."name" ILIKE '%MILTON GUSTAVO%' )
OR (prison_person.last_name ILIKE '%VEGA GUALAN %' OR prison_person."name" ILIKE '%EDISON AGUSTIN%' )
OR (prison_person.last_name ILIKE '%CHIGUANO NARVAEZ %' OR prison_person."name" ILIKE '%JAVIER PATRICIO%' )
OR (prison_person.last_name ILIKE '%ARIAS TURA %' OR prison_person."name" ILIKE '%ELMER PABLO%' )
OR (prison_person.last_name ILIKE '%LOBATON CAGUA %' OR prison_person."name" ILIKE '%VICTOR JULIO%' )
OR (prison_person.last_name ILIKE '%BRAVO SANTANA %' OR prison_person."name" ILIKE '%CARLOS FELIPE%' )
OR (prison_person.last_name ILIKE '%CHANGO TAMAYO %' OR prison_person."name" ILIKE '%LUIS FERNANDO%' )
OR (prison_person.last_name ILIKE '%JARAMILLO DOMO %' OR prison_person."name" ILIKE '%EDISON ISRAEL%' )
OR (prison_person.last_name ILIKE '%VILLALTA PINGUIL %' OR prison_person."name" ILIKE '%VICTOR ALFONSO%' )
OR (prison_person.last_name ILIKE '%JACOME ARBOLEDA %' OR prison_person."name" ILIKE '%DIEGO MARCELO%' )
OR (prison_person.last_name ILIKE '%GUAMANGALLO GARRIDO %' OR prison_person."name" ILIKE '%RICARDO DANIEL%' )
OR (prison_person.last_name ILIKE '%SMITH PLAZA %' OR prison_person."name" ILIKE '%JEAN CARLOS%' )
OR (prison_person.last_name ILIKE '%FEIJO COSOS %' OR prison_person."name" ILIKE '%LENIN STALIN%' )
OR (prison_person.last_name ILIKE '%MORALES MENESES %' OR prison_person."name" ILIKE '%BRANDON DANIEL%' )
OR (prison_person.last_name ILIKE '%CAHUASQUI GUAMAN%' OR prison_person."name" ILIKE '%JAIME RODRIGO %' )
OR (prison_person.last_name ILIKE '%CASTILLO PAREDES%' OR prison_person."name" ILIKE '%JHON JAIRO  %' )
OR (prison_person.last_name ILIKE '%ESTRADA QUIÑONEZ%' OR prison_person."name" ILIKE '%ITALO ANTONIO %' )
OR (prison_person.last_name ILIKE '%VALDEZ HIGUERA%' OR prison_person."name" ILIKE '%FRANK LEONEL %' )
OR (prison_person.last_name ILIKE '%ZAMBRANO SUAREZ%' OR prison_person."name" ILIKE '%JAWIEN %' )
OR (prison_person.last_name ILIKE '%VILLA HERNANDEZ%' OR prison_person."name" ILIKE '%JORGE MILLER %' )
OR (prison_person.last_name ILIKE '%CABRERA PERALTA%' OR prison_person."name" ILIKE '%ERMEN DEONANTE %' )
OR (prison_person.last_name ILIKE '%FELIX VALENZUELA%' OR prison_person."name" ILIKE '%JESUS ALFREDO %' )
OR (prison_person.last_name ILIKE '%LOAIZA MONZON%' OR prison_person."name" ILIKE '%SALVADOR %' )
OR (prison_person.last_name ILIKE '%YANQUI LOYA%' OR prison_person."name" ILIKE '%ALEX ANIBAL%' )
OR (prison_person.last_name ILIKE '%ZAMBRANO CEDEÑO%' OR prison_person."name" ILIKE '%JOSE MEDARDO %' )
OR (prison_person.last_name ILIKE '%MUÑOZ CHAVARRO%' OR prison_person."name" ILIKE '%JOSE ORLANDOM %' )
OR (prison_person.last_name ILIKE '%AGUIRRE PARRALES%' OR prison_person."name" ILIKE '%JHONY LEONEL%' )
OR (prison_person.last_name ILIKE '%DOCHEV STANISLAV%' OR prison_person."name" ILIKE '%GEORGIEV%' )
OR (prison_person.last_name ILIKE '%CRUZ CORONADO%' OR prison_person."name" ILIKE '%PATRICIO DAVID%' )
OR (prison_person.last_name ILIKE '%VELOZ ALDAZ%' OR prison_person."name" ILIKE '%MARIO DAVID %' )
OR (prison_person.last_name ILIKE '%CASTRO PACHACAMA%' OR prison_person."name" ILIKE '%JONATHAN ALEXANDER%' )
OR (prison_person.last_name ILIKE '%SALTOS DE LA CRUZ%' OR prison_person."name" ILIKE '%EDUARDO MANUEL %' )
OR (prison_person.last_name ILIKE '%LOOR MALAGA%' OR prison_person."name" ILIKE '%CELI RAMON%' )
OR (prison_person.last_name ILIKE '%MONTENEGRO IMBAQUINGO%' OR prison_person."name" ILIKE '%DAVID SANTIAGO%' )
OR (prison_person.last_name ILIKE '%TERAN TUQUERRES%' OR prison_person."name" ILIKE '%LUIS ENRIQUE %' )
OR (prison_person.last_name ILIKE '%ALQUINGA ALQUINGA%' OR prison_person."name" ILIKE '%BRAULIO ALCIDES %' )
OR (prison_person.last_name ILIKE '%HERRERA ZAPATA%' OR prison_person."name" ILIKE '%JUAN DAVID %' )
OR (prison_person.last_name ILIKE '%HERNANDEZ DIAS%' OR prison_person."name" ILIKE '%MANUEL GREGORIO%' )
OR (prison_person.last_name ILIKE '%BAÑO GARCES%' OR prison_person."name" ILIKE '%JEAN CARLOS%' )
OR (prison_person.last_name ILIKE '%MENDOZA BAILON%' OR prison_person."name" ILIKE '%PEDRO DARWIN%' )
OR (prison_person.last_name ILIKE '%VEGA MANOTOA%' OR prison_person."name" ILIKE '%FAUSTO JOSE %' )
OR (prison_person.last_name ILIKE '%SAPA CHUNLLI%' OR prison_person."name" ILIKE '%FRANKLIN RODRIGO%' )
OR (prison_person.last_name ILIKE '%GUERRA GONZALES%' OR prison_person."name" ILIKE '%LUIS ALBERTO %' )
OR (prison_person.last_name ILIKE '%LABRADOR OLAGUEZ%' OR prison_person."name" ILIKE '%JUAN MARCO %' )
OR (prison_person.last_name ILIKE '%CHAVEZ%' OR prison_person."name" ILIKE '%JORGE GABRIEL %' )
OR (prison_person.last_name ILIKE '%MEZA PEREGRINA%' OR prison_person."name" ILIKE '%JUAN RIGOBERTO %' )
OR (prison_person.last_name ILIKE '%FERRIN CUSME%' OR prison_person."name" ILIKE '%ANGEL ALFREDO%' )
OR (prison_person.last_name ILIKE '%LEON ROSERO%' OR prison_person."name" ILIKE '%ALFREDO RAUL %' )
OR (prison_person.last_name ILIKE '%MAMALLACTA%' OR prison_person."name" ILIKE '%QUINTERO MARCO ELIAS %' )
OR (prison_person.last_name ILIKE '%MONTAÑO TOLEDO%' OR prison_person."name" ILIKE '%MARCOS RICHARD%' )
OR (prison_person.last_name ILIKE '%PINARGOTE TRIANA%' OR prison_person."name" ILIKE '%MARCO ANTONIO %' )
OR (prison_person.last_name ILIKE '%ROLDAN INTRIAGO%' OR prison_person."name" ILIKE '%JOSE FELIPE %' )
OR (prison_person.last_name ILIKE '%VERA GAONA%' OR prison_person."name" ILIKE '%YORDAN FRANKLIN %' )
OR (prison_person.last_name ILIKE '%VERDEZOTO MORENO%' OR prison_person."name" ILIKE '%MIGUEL ANGEL%' )
OR (prison_person.last_name ILIKE '%ESPINOZA MENDEZ%' OR prison_person."name" ILIKE '%HECTOR ADOLFO %' )
OR (prison_person.last_name ILIKE '%FUENTES LOPEZ%' OR prison_person."name" ILIKE '%MILTON %' )
OR (prison_person.last_name ILIKE '%TUCANES CHALAPUD%' OR prison_person."name" ILIKE '%MARCOS ALIRIO%' )
OR (prison_person.last_name ILIKE '%SANCHEZ MENA%' OR prison_person."name" ILIKE '%JORGE LUIS %' )
OR (prison_person.last_name ILIKE '%LLUMIQUINGA MANRIQUE%' OR prison_person."name" ILIKE '%ROBERTO DAVID %' )
OR (prison_person.last_name ILIKE '%CARDENAS TAPIA%' OR prison_person."name" ILIKE '%BRYAN ALEXANDER %' )
OR (prison_person.last_name ILIKE '%YUCAILLA YUCAILLA%' OR prison_person."name" ILIKE '%JOSE %' )
OR (prison_person.last_name ILIKE '%MOSQUERA RUANO%' OR prison_person."name" ILIKE '%RICARDO %' )
OR (prison_person.last_name ILIKE '%CHAVEZ ZABALA%' OR prison_person."name" ILIKE '%LUIS FERNANDO %' )
OR (prison_person.last_name ILIKE '%QUINTERO QUINTERO%' OR prison_person."name" ILIKE '%CESAR ALBERTO%' )
OR (prison_person.last_name ILIKE '%QUISHPE DIAZ%' OR prison_person."name" ILIKE '%CRISTIAN MANUEL%' )
OR (prison_person.last_name ILIKE '%CIPRIANI%' OR prison_person."name" ILIKE '%GAETANO%' )
OR (prison_person.last_name ILIKE '%MACAS COLOMA%' OR prison_person."name" ILIKE '%BENIGNO ADALBERTO%' )
OR (prison_person.last_name ILIKE '%BONE RIVERA%' OR prison_person."name" ILIKE '%WILSON LENIN %' )
OR (prison_person.last_name ILIKE '%POZO VIRACOCHA%' OR prison_person."name" ILIKE '%ANDERSON DAVID %' )
OR (prison_person.last_name ILIKE '%TANDALLA TOAPANTA%' OR prison_person."name" ILIKE '%CRISTHIAN RAFAEL%' )
OR (prison_person.last_name ILIKE '%VILLEGAS MONAR%' OR prison_person."name" ILIKE '%NOE VLADIMIR%' )
OR (prison_person.last_name ILIKE '%ARTEAGA ROSERO%' OR prison_person."name" ILIKE '%ELIAS OVIDIO %' )
OR (prison_person.last_name ILIKE '%CASTRO PEÑA%' OR prison_person."name" ILIKE '%IVERT %' )
OR (prison_person.last_name ILIKE '%SIMBAÑA TUTASHI%' OR prison_person."name" ILIKE '%JAVIER VINICIO%' )
OR (prison_person.last_name ILIKE '%ENRIQUEZ NARANJO%' OR prison_person."name" ILIKE '%DARWIN MARCELO %' )
OR (prison_person.last_name ILIKE '%CHASILUISA ARCOS%' OR prison_person."name" ILIKE '%BRANDON EDISON%' )
OR (prison_person.last_name ILIKE '%REASCOS GAMBOA%' OR prison_person."name" ILIKE '%EDISON GUSTAVO %' )
OR (prison_person.last_name ILIKE '%MOLINA CRUZ%' OR prison_person."name" ILIKE '%CARLOS ALBERTO %' )
OR (prison_person.last_name ILIKE '%MORA LOMBEIDA%' OR prison_person."name" ILIKE '%TELMO EURODO %' )
OR (prison_person.last_name ILIKE '%TOAPANTA AREQUIPA%' OR prison_person."name" ILIKE '%SEGUNDO RAFAEL%' )
OR (prison_person.last_name ILIKE '%CRUZ TOMALA%' OR prison_person."name" ILIKE '%JOSE ALBERTO %' )
OR (prison_person.last_name ILIKE '%RODRIGUEZ VALERIANO%' OR prison_person."name" ILIKE '%JOSE LUIS  %' )
OR (prison_person.last_name ILIKE '%DURAN GALLEGOS%' OR prison_person."name" ILIKE '%FREDDY PATRICIO%' )
OR (prison_person.last_name ILIKE '%CAYO UNDA%' OR prison_person."name" ILIKE '%NELSON OSWALDO %' )
OR (prison_person.last_name ILIKE '%ANDRADE SANDOVAL%' OR prison_person."name" ILIKE '%JOFRE DANIEL%' )
OR (prison_person.last_name ILIKE '%CARRILLO CORONEL%' OR prison_person."name" ILIKE '%SIMON BOLIVAR%' )
OR (prison_person.last_name ILIKE '%QUISHPE TORRES%' OR prison_person."name" ILIKE '%ANDERSON JOEL %' )
OR (prison_person.last_name ILIKE '%PINEDA RODRIGUEZ%' OR prison_person."name" ILIKE '%FRANKLIN FRANCISCO %' )
OR (prison_person.last_name ILIKE '%ROSALESANGULO%' OR prison_person."name" ILIKE '%FERNEY ALFREDO%' )
OR (prison_person.last_name ILIKE '%YANEZ CRUZ%' OR prison_person."name" ILIKE '%KENNY JOSE %' )
OR (prison_person.last_name ILIKE '%MEJIA CARDENAS%' OR prison_person."name" ILIKE '%JOSE LUIS %' )
OR (prison_person.last_name ILIKE '%TORRES LOPEZ%' OR prison_person."name" ILIKE '%JAMES EIDER %' )
OR (prison_person.last_name ILIKE '%LOPEZ BRAVO%' OR prison_person."name" ILIKE '%JOSE GERARDO%' )
OR (prison_person.last_name ILIKE '%QUISHPEARCOS%' OR prison_person."name" ILIKE '%EDGAR ANDRES %' )
OR (prison_person.last_name ILIKE '%CAHUANO CASTRO%' OR prison_person."name" ILIKE '%NILO MESIAS %' )
OR (prison_person.last_name ILIKE '%TIPAN CENTENO%' OR prison_person."name" ILIKE '%ALEX FERNANDO %' )
OR (prison_person.last_name ILIKE '%ZAMBRANO VERA%' OR prison_person."name" ILIKE '%GALO CECILIO %' )
OR (prison_person.last_name ILIKE '%CONDE BRAVO%' OR prison_person."name" ILIKE '%JOHAN SAMIR %' )
OR (prison_person.last_name ILIKE '%SILVA MARTINEZ%' OR prison_person."name" ILIKE '%HENRY DANIEL %' )
OR (prison_person.last_name ILIKE '%VILLAFUERTE SINGO%' OR prison_person."name" ILIKE '%MARCO VINICIO%' )
OR (prison_person.last_name ILIKE '%GOMEZ PANTOJA%' OR prison_person."name" ILIKE '%EDWIN ANDRES%' )
OR (prison_person.last_name ILIKE '%RECALDE LEYTON%' OR prison_person."name" ILIKE '%EVER FERNANDO %' )
OR (prison_person.last_name ILIKE '%ALVARADO CAMPAGNE%' OR prison_person."name" ILIKE '%JESUS OMAR %' )
OR (prison_person.last_name ILIKE '%ARAGON GONZALEZ%' OR prison_person."name" ILIKE '%LUIS ANTONIO %' )
OR (prison_person.last_name ILIKE '%CHUNG JURADO%' OR prison_person."name" ILIKE '%ALVARO RAUL %' )
OR (prison_person.last_name ILIKE '%PEÑAFIEL PAREDES%' OR prison_person."name" ILIKE '%RONN RICARDO%' )
OR (prison_person.last_name ILIKE '%OSUNA BELTRAN%' OR prison_person."name" ILIKE '%LUIS ALBERTO %' )
OR (prison_person.last_name ILIKE '%REYES CANALES%' OR prison_person."name" ILIKE '%DANIEL %' )
OR (prison_person.last_name ILIKE '%VALDEZ REYES%' OR prison_person."name" ILIKE '%MANUEL%' )
OR (prison_person.last_name ILIKE '%BENAVIDESESPAÑA%' OR prison_person."name" ILIKE '%EDISON ANDRES %' )
OR (prison_person.last_name ILIKE '%PORRAS AREQUIPA%' OR prison_person."name" ILIKE '%LUIS FERNANDO%' )
OR (prison_person.last_name ILIKE '%CHICAIZA QUISHPE%' OR prison_person."name" ILIKE '%JIMMY GUSTAVO%' )
OR (prison_person.last_name ILIKE '%RIVAS VALENCIA%' OR prison_person."name" ILIKE '%JORDY ANDRES%' )
OR (prison_person.last_name ILIKE '%BARONA RODRIGUEZ%' OR prison_person."name" ILIKE '%ANDERSON STEVEN  %' )
OR (prison_person.last_name ILIKE '%JACOME LOPEZ%' OR prison_person."name" ILIKE '%JASON NAPOLEON %' )
OR (prison_person.last_name ILIKE '%QUIDIGUA MORALES%' OR prison_person."name" ILIKE '%JESUS ENRIQUE%' )
OR (prison_person.last_name ILIKE '%RAMIREZ ARAGON%' OR prison_person."name" ILIKE '%DIOGENES MANUEL%' )
OR (prison_person.last_name ILIKE '%ILAQUICHE TIGASI%' OR prison_person."name" ILIKE '%CESAR ERNESTO %' )
OR (prison_person.last_name ILIKE '%CORAL PEREZ%' OR prison_person."name" ILIKE '%LUIS JAIME%' )
OR (prison_person.last_name ILIKE '%JANETA PARDO%' OR prison_person."name" ILIKE '%DANNY EMERSON%' )
OR (prison_person.last_name ILIKE '%ARTEAGA BETANCORTH%' OR prison_person."name" ILIKE '%JAIRO ANDRES %' )
OR (prison_person.last_name ILIKE '%SALAZAR ABAD%' OR prison_person."name" ILIKE '%MANUEL ALBERTO  %' )
OR (prison_person.last_name ILIKE '%RIOS FRUCTUOSO%' OR prison_person."name" ILIKE '%JUAN AURELIO%' )
OR (prison_person.last_name ILIKE '%ALARCON OLAVE%' OR prison_person."name" ILIKE '%ARIEL DAVID%' )
OR (prison_person.last_name ILIKE '%DUEÑAS NARANJO%' OR prison_person."name" ILIKE '%PABLO VINICIO%' )
OR (prison_person.last_name ILIKE '%MEDINA GARCES %' OR prison_person."name" ILIKE '%VICTOR HUGO%' )
OR (prison_person.last_name ILIKE '%LLIQUIN SALVATIERRA%' OR prison_person."name" ILIKE '%LUIS FERNANDO %' )
OR (prison_person.last_name ILIKE '%YACELGA BENAVIDES%' OR prison_person."name" ILIKE '%GUSTAVO BLADIMIR%' )
OR (prison_person.last_name ILIKE '%GUACHAMIN VASQUEZ%' OR prison_person."name" ILIKE '%WASHINGTON OSWALDO%' )
OR (prison_person.last_name ILIKE '%RAMOS AVALA DANNY%' OR prison_person."name" ILIKE '%VICENTE%' )
OR (prison_person.last_name ILIKE '%RAMOS AVALA MARCOS%' OR prison_person."name" ILIKE '%FERNANDO %' )
OR (prison_person.last_name ILIKE '%SILVA GUEVARA%' OR prison_person."name" ILIKE '%CARLOS FRANCISCO%' )
OR (prison_person.last_name ILIKE '%TOAQUIZA CAISAGUANO%' OR prison_person."name" ILIKE '%JOSE MARCELO%' )
OR (prison_person.last_name ILIKE '%QUINGATUÑA BONILLA%' OR prison_person."name" ILIKE '%EDISON ADRIAN %' )
OR (prison_person.last_name ILIKE '%TIGSELEMA CORNELIO%' OR prison_person."name" ILIKE '%JOSE WALBERTO %' )
OR (prison_person.last_name ILIKE '%RICO GAVILANES%' OR prison_person."name" ILIKE '%PEDRO PABLO  %' )
OR (prison_person.last_name ILIKE '%RAMOS RAMOS%' OR prison_person."name" ILIKE '%WILLIAM PATRICIO %' )
OR (prison_person.last_name ILIKE '%SORIA ESPINOZA%' OR prison_person."name" ILIKE '%NESTOR GONZALO%' )
OR (prison_person.last_name ILIKE '%VACA CABASCANGO%' OR prison_person."name" ILIKE '%OMAR RENE%' )
OR (prison_person.last_name ILIKE '%VACA PALMA%' OR prison_person."name" ILIKE '%DANIEL MICHAEL %' )
OR (prison_person.last_name ILIKE '%VEGA CAYO%' OR prison_person."name" ILIKE '%RAUL ALEJANDRO %' )
OR (prison_person.last_name ILIKE '%MUÑOZ ALVARADO%' OR prison_person."name" ILIKE '%DONAL NIETO%' )
OR (prison_person.last_name ILIKE '%ANDY MAMALLACTA%' OR prison_person."name" ILIKE '%JAIRO DANIEL %' )
OR (prison_person.last_name ILIKE '%CHIMBO PILCO%' OR prison_person."name" ILIKE '%LUIS ALFREDO%' )
OR (prison_person.last_name ILIKE '%ESQUIVEL ORTIZ%' OR prison_person."name" ILIKE '%JESUS DANIEL%' )
OR (prison_person.last_name ILIKE '%ROSERO CORONADO%' OR prison_person."name" ILIKE '%JEFFERSON JAVIER%' )
OR (prison_person.last_name ILIKE '%ROSERO DIAZ%' OR prison_person."name" ILIKE '%JESUS LAURENCIO%' )
OR (prison_person.last_name ILIKE '%HERRERA NARANJO%' OR prison_person."name" ILIKE '%CARLOS ANDRES %' )
OR (prison_person.last_name ILIKE '%VALLEJO PESANTE%' OR prison_person."name" ILIKE '%BORIS EDISON %' )
OR (prison_person.last_name ILIKE '%NAZARENO PALMA%' OR prison_person."name" ILIKE '%JUAN JOSE %' )
OR (prison_person.last_name ILIKE '%MARQUINEZ VELASQUEZ%' OR prison_person."name" ILIKE '%CARLOS EDISON %' )
OR (prison_person.last_name ILIKE '%ARMAS QUIROZ%' OR prison_person."name" ILIKE '%LUIS ANGEL%' )
OR (prison_person.last_name ILIKE '%ASITIMBAY GUARANGO%' OR prison_person."name" ILIKE '%MIGUEL ANGEL%' )
OR (prison_person.last_name ILIKE '%GREFA USHIGUA%' OR prison_person."name" ILIKE '%WILLIAM CAMILO%' )
OR (prison_person.last_name ILIKE '%PEAZA JARA%' OR prison_person."name" ILIKE '%ROLANDO IVAN%' )
OR (prison_person.last_name ILIKE '%INTRIAGO BRAVO%' OR prison_person."name" ILIKE '%LUIS ORLANDO %' )
OR (prison_person.last_name ILIKE '%PETKOVIC %' OR prison_person."name" ILIKE '%VLADIMIR%' )
OR (prison_person.last_name ILIKE '%DIAZ VARGAS%' OR prison_person."name" ILIKE '%PEDRO PABLO%' )
OR (prison_person.last_name ILIKE '%GUAMANI TIPANLUISA%' OR prison_person."name" ILIKE '%BRYAN IVAN %' )
OR (prison_person.last_name ILIKE '%CASTRO ANALUCA%' OR prison_person."name" ILIKE '%PAUL WILLIAN%' )
OR (prison_person.last_name ILIKE '%SIMBAÑA SIMBAÑA%' OR prison_person."name" ILIKE '%FEDERICO %' )
OR (prison_person.last_name ILIKE '%SIERRA LOPEZ%' OR prison_person."name" ILIKE '%CARLOS ALBERTO%' )
OR (prison_person.last_name ILIKE '%DELGADO VILLARRIAL%' OR prison_person."name" ILIKE '%SEGUNDO ALBEIRO%' )
OR (prison_person.last_name ILIKE '%ESQUIVEL RIOS%' OR prison_person."name" ILIKE '%JORGE ANDRES %' )
OR (prison_person.last_name ILIKE '%DELGADO VILLOTA%' OR prison_person."name" ILIKE '%JOSE LUIS  %' )
OR (prison_person.last_name ILIKE '%HURTADO VELA%' OR prison_person."name" ILIKE '%JUAN CARLOS %' )
OR (prison_person.last_name ILIKE '%NICOLTA MOSQUERA%' OR prison_person."name" ILIKE '%DANNY JAVIER %' )
OR (prison_person.last_name ILIKE '%VELASQUEZ MOSQUERA%' OR prison_person."name" ILIKE '%JOSE RICARDO %' )
OR (prison_person.last_name ILIKE '%FUERTES TULCAN%' OR prison_person."name" ILIKE '%JOSE MANUEL%' )
OR (prison_person.last_name ILIKE '%MENDEZ CARVALLO%' OR prison_person."name" ILIKE '%ELISAUL THESMI %' )
OR (prison_person.last_name ILIKE '%CHASSI CELA%' OR prison_person."name" ILIKE '%MARCO VINICIO %' )
OR (prison_person.last_name ILIKE '%MARTINEZ OCHOA%' OR prison_person."name" ILIKE '%KEVIN DANILO %' )
OR (prison_person.last_name ILIKE '%MONRROY RODRIGUEZ%' OR prison_person."name" ILIKE '%GUSTAVO FABRICIO%' )
OR (prison_person.last_name ILIKE '%TOPON CUICHAN%' OR prison_person."name" ILIKE '%EDISON GEOVANNAY%' )
OR (prison_person.last_name ILIKE '%BASTIDAS LOPEZ%' OR prison_person."name" ILIKE '%MARLON ALEXANDER %' )
OR (prison_person.last_name ILIKE '%SANTANA YELAMO%' OR prison_person."name" ILIKE '%NERVI FRANCISCO%' )
OR (prison_person.last_name ILIKE '%MOLINA SALAZAR%' OR prison_person."name" ILIKE '%FERNANDO MAXIMILIANO %' )
OR (prison_person.last_name ILIKE '%CASTILLO  %' OR prison_person."name" ILIKE '%JHON NYFER%' )
OR (prison_person.last_name ILIKE '%SAAVEDRA MORALES%' OR prison_person."name" ILIKE '%TELMO ALBERTO %' )
OR (prison_person.last_name ILIKE '%CHICHANDA ZAMBRANO%' OR prison_person."name" ILIKE '%DIOMEDES MEDARDO %' )
OR (prison_person.last_name ILIKE '%POZO SAAVEDRA%' OR prison_person."name" ILIKE '%MARCO ALCIDE  %' )
OR (prison_person.last_name ILIKE '%BELYAEV%' OR prison_person."name" ILIKE '%ALBERT %' )
OR (prison_person.last_name ILIKE '%FAJARDO VARGAS%' OR prison_person."name" ILIKE '%YAIRON JONATHAN %' )
OR (prison_person.last_name ILIKE '%QUINATOA AMAYA%' OR prison_person."name" ILIKE '%JOSE ALFONSO%' )
OR (prison_person.last_name ILIKE '%SANDOVAL MONTESDEOCA%' OR prison_person."name" ILIKE '%FERNANDO BOLIVAR%' )
OR (prison_person.last_name ILIKE '%VELASCO VELASCO%' OR prison_person."name" ILIKE '%ABEL RENATO %' )
OR (prison_person.last_name ILIKE '%NAPA MONTEZUMA%' OR prison_person."name" ILIKE '%MAURO NARCILO %' )
OR (prison_person.last_name ILIKE '%CONDOR LAMIÑA%' OR prison_person."name" ILIKE '%WILMER PAUL %' )
OR (prison_person.last_name ILIKE '%VERDUGA LOOR%' OR prison_person."name" ILIKE '%LUIS MIGUEL %' )
OR (prison_person.last_name ILIKE '%VILLAFUERTE SUAREZ%' OR prison_person."name" ILIKE '%FRANCISCO JAVIER %' )
OR (prison_person.last_name ILIKE '%LITARDO BARCO%' OR prison_person."name" ILIKE '%JUSTINO HUMBERTO %' )
OR (prison_person.last_name ILIKE '%PINCAY MENDOZA%' OR prison_person."name" ILIKE '%JUAN GABRIEL %' )
OR (prison_person.last_name ILIKE '%AYOVI HERNANDEZ%' OR prison_person."name" ILIKE '%DILO LUIS %' )
OR (prison_person.last_name ILIKE '%GRACIA VASQUEZ%' OR prison_person."name" ILIKE '%CARLOS JULIO %' )
OR (prison_person.last_name ILIKE '%CRUEL MORENO%' OR prison_person."name" ILIKE '%JORGE PUBLIO %' )
OR (prison_person.last_name ILIKE '%DAVILA PEREZ%' OR prison_person."name" ILIKE '%JUAN JOSE %' )
OR (prison_person.last_name ILIKE '%GARCIA HERRERIA%' OR prison_person."name" ILIKE '%PATRICIO %' )
OR (prison_person.last_name ILIKE '%NAVARRO RAMIREZ%' OR prison_person."name" ILIKE '%MARIO ANDRES %' )
OR (prison_person.last_name ILIKE '%BASTIDAS BUSTAN%' OR prison_person."name" ILIKE '%LUIS DE CARLO%' )
OR (prison_person.last_name ILIKE '%QUINTERO MURILLO%' OR prison_person."name" ILIKE '%WASHINGTON ROLANDO%' )
OR (prison_person.last_name ILIKE '%SIERRA TENORIO%' OR prison_person."name" ILIKE '%HUGO WALBERTO%' )
OR (prison_person.last_name ILIKE '%CAIZA GUATEMAL%' OR prison_person."name" ILIKE '%WILSON PAUL %' )
OR (prison_person.last_name ILIKE '%CARVAJAL CABEZAS%' OR prison_person."name" ILIKE '%JORGE STALYN %' )
OR (prison_person.last_name ILIKE '%REYES ORTIZ%' OR prison_person."name" ILIKE '%ALBERTO JOSELITO %' )
OR (prison_person.last_name ILIKE '%SANCHEZ PLAZA%' OR prison_person."name" ILIKE '%JORDAN OSWALDO %' )
OR (prison_person.last_name ILIKE '%QUISHPE MALUSIN%' OR prison_person."name" ILIKE '%JAIME VINICIO %' )
OR (prison_person.last_name ILIKE '%LOPEZ JIMENEZ%' OR prison_person."name" ILIKE '%HUGO HERNAN %' )
OR (prison_person.last_name ILIKE '%MIRANDA YUMBO%' OR prison_person."name" ILIKE '%CRISTIAN RAMIRO %' )
OR (prison_person.last_name ILIKE '%TORRES BARAJA%' OR prison_person."name" ILIKE '%PEDRO ELIODORO %' )
OR (prison_person.last_name ILIKE '%BERMELLO REZABALA%' OR prison_person."name" ILIKE '%JHONNY JAVIER %' )
OR (prison_person.last_name ILIKE '%CAHUA INTRIAGO%' OR prison_person."name" ILIKE '%BYRON GABRIEL %' )
OR (prison_person.last_name ILIKE '%MALPU GUARANGUAY%' OR prison_person."name" ILIKE '%SIMON BOLIVAR %' )
OR (prison_person.last_name ILIKE '%CARLOSAMA FARINANGO%' OR prison_person."name" ILIKE '%ALFREDO %' )
OR (prison_person.last_name ILIKE '%ALMEIDA ESPINOZA%' OR prison_person."name" ILIKE '%GALO ALFREDO %' )
OR (prison_person.last_name ILIKE '%ANGULO CORTEZ%' OR prison_person."name" ILIKE '%JHONN JAIRO %' )
OR (prison_person.last_name ILIKE '%CACUANGO MALDONADO%' OR prison_person."name" ILIKE '%EDISON FREDDY %' )
OR (prison_person.last_name ILIKE '%SALAS TORRES%' OR prison_person."name" ILIKE '%RICHARD RAMIRO%' )
OR (prison_person.last_name ILIKE '%SOLIS IZURIETA%' OR prison_person."name" ILIKE '%EDMUNDO EUSTORGIO %' )
OR (prison_person.last_name ILIKE '%YAMBERLA MALDONADO%' OR prison_person."name" ILIKE '%WILMER JAIRO%' )
OR (prison_person.last_name ILIKE '%YEPEZ HURTADO%' OR prison_person."name" ILIKE '%LUIS GONZALO %' )
OR (prison_person.last_name ILIKE '%ZUÑIGA VELASCO%' OR prison_person."name" ILIKE '%YANYINER%' )
OR (prison_person.last_name ILIKE '%BORJA IZURIETA%' OR prison_person."name" ILIKE '%CARLOS EDUARDO%' )
OR (prison_person.last_name ILIKE '%CANTUÑA MOSQUERA%' OR prison_person."name" ILIKE '%WILMER AUGUSTO%' )
OR (prison_person.last_name ILIKE '%CASANOVA MORA%' OR prison_person."name" ILIKE '%ARNULFO PATRICIO %' )
OR (prison_person.last_name ILIKE '%HENAO MEZA%' OR prison_person."name" ILIKE '%SERGIO ANDRES%' )
OR (prison_person.last_name ILIKE '%ORTEGA HERRERA%' OR prison_person."name" ILIKE '%TULIO ANDRES%' )
OR (prison_person.last_name ILIKE '%CHAVEZ QUIÑONEZ%' OR prison_person."name" ILIKE '%IVAN AUGUSTO%' )
OR (prison_person.last_name ILIKE '%GOMEZ BAZURTO%' OR prison_person."name" ILIKE '%RONNY ALBERTO %' )
OR (prison_person.last_name ILIKE '%CARRANZA GANCHOZO%' OR prison_person."name" ILIKE '%DIOGENES ENRIQUE%' )
OR (prison_person.last_name ILIKE '%CEDEÑO DIAZ%' OR prison_person."name" ILIKE '%LUIS ANTONIO%' )
OR (prison_person.last_name ILIKE '%CEDEÑO MACIAS%' OR prison_person."name" ILIKE '%JONATHAN JOSE%' )
OR (prison_person.last_name ILIKE '%CHAVEZ LOPEZ%' OR prison_person."name" ILIKE '%ORLEY GERMAN%' )
OR (prison_person.last_name ILIKE '%COOX VERA%' OR prison_person."name" ILIKE '%OLINPO YOVANNY%' )
OR (prison_person.last_name ILIKE '%GANCHOZO VELEZ%' OR prison_person."name" ILIKE '%WALTHER RAMON %' )
OR (prison_person.last_name ILIKE '%GARCIA TOAQUIZA%' OR prison_person."name" ILIKE '%EDISON JAVIER %' )
OR (prison_person.last_name ILIKE '%OLMEDO PICO%' OR prison_person."name" ILIKE '%JILMER BAUDIL%' )
OR (prison_person.last_name ILIKE '%VERDEZOTO TAPIA%' OR prison_person."name" ILIKE '%DANY DAVID%' )
OR (prison_person.last_name ILIKE '%YUMBO ANDI%' OR prison_person."name" ILIKE '%JOSE ANDRES %' )
OR (prison_person.last_name ILIKE '%ERAZO VERGARA%' OR prison_person."name" ILIKE '%JORBELIZ PERBLEY %' )
OR (prison_person.last_name ILIKE '%FARINANGO IPIALES%' OR prison_person."name" ILIKE '%LUIS ALFONSO %' )
OR (prison_person.last_name ILIKE '%MANTECA CONGO%' OR prison_person."name" ILIKE '%CRISTIAN ROBERTO%' )
OR (prison_person.last_name ILIKE '%VASQUEZ ANDRADE%' OR prison_person."name" ILIKE '%JUAN CARLOS%' )
OR (prison_person.last_name ILIKE '%VERA OLALLA%' OR prison_person."name" ILIKE '%XAVIER BENEY%' )
OR (prison_person.last_name ILIKE '%NAJERA LEON%' OR prison_person."name" ILIKE '%EDWARD PAUL %' )
OR (prison_person.last_name ILIKE '%VELEZ DELGADO%' OR prison_person."name" ILIKE '%JOSE GREGORIO%' )
OR (prison_person.last_name ILIKE '%GONZALEZ PINEDA%' OR prison_person."name" ILIKE '%STALIN ROBERTO%' )
OR (prison_person.last_name ILIKE '%PILAMUNGA PALTAN%' OR prison_person."name" ILIKE '%DIONICIO%' )
OR (prison_person.last_name ILIKE '%BAEZ PIAMONTE%' OR prison_person."name" ILIKE '%CARLOS LUIS %' )
OR (prison_person.last_name ILIKE '%ROJAS ROJAS%' OR prison_person."name" ILIKE '%PABLO FERNANDO%' )
OR (prison_person.last_name ILIKE '%DELGADO FLORES%' OR prison_person."name" ILIKE '%JESUS ALEJANDRO%' )
OR (prison_person.last_name ILIKE '%POAQUIZA NATA%' OR prison_person."name" ILIKE '%MILTON RODRIGO%' )
OR (prison_person.last_name ILIKE '%SANCHEZ MARCHAND%' OR prison_person."name" ILIKE '%ROBERTO ANIBAL %' )
OR (prison_person.last_name ILIKE '%DURAN CAIZA%' OR prison_person."name" ILIKE '%MAURICIO FERNANDO %' )
OR (prison_person.last_name ILIKE '%CORREA VILLEGAS%' OR prison_person."name" ILIKE '%JEISON ALEXIS %' )
OR (prison_person.last_name ILIKE '%NOLIVOS NIAUPARI%' OR prison_person."name" ILIKE '%RENATO VLADIMIR %' )
OR (prison_person.last_name ILIKE '%SANCHEZ BARRE%' OR prison_person."name" ILIKE '%EDISON ALEJANDRO %' )
OR (prison_person.last_name ILIKE '%CABRERA YELA%' OR prison_person."name" ILIKE '%ROBINSON DUVAN %' )
OR (prison_person.last_name ILIKE '%LEMA SUMI%' OR prison_person."name" ILIKE '%CARLOS ALBERTO %' )
OR (prison_person.last_name ILIKE '%PARRAGA BASURTO%' OR prison_person."name" ILIKE '%LIDER LENIN %' )
OR (prison_person.last_name ILIKE '%FRANCO RAMIREZ%' OR prison_person."name" ILIKE '%SANTIAGO ISRAEL %' )
OR (prison_person.last_name ILIKE '%JURADO CASTRO%' OR prison_person."name" ILIKE '%MILTON RAMIRO %' )
OR (prison_person.last_name ILIKE '%PATEL AMIT%' OR prison_person."name" ILIKE '%JAYANTILAL %' )
OR (prison_person.last_name ILIKE '%ESPINOSA TUMIPAMBA%' OR prison_person."name" ILIKE '%VICTOR ROLANDO %' )
OR (prison_person.last_name ILIKE '%TAYO SURA%' OR prison_person."name" ILIKE '%VICTOR MARCELO %' )
OR (prison_person.last_name ILIKE '%ANDACHE ANDACHI%' OR prison_person."name" ILIKE '%IGNACIO RIGOBERTO %' )
OR (prison_person.last_name ILIKE '%HERNANDEZ LONDOÑO%' OR prison_person."name" ILIKE '%JHONATAN ALEXANDER %' )
OR (prison_person.last_name ILIKE '%IPIALES CLAUDIO%' OR prison_person."name" ILIKE '%EDGAR PAUL%' )
OR (prison_person.last_name ILIKE '%ARBELAEZ ZAPATA%' OR prison_person."name" ILIKE '%JUAN DANIEL %' )
OR (prison_person.last_name ILIKE '%LUZURIAGA ORTIZ%' OR prison_person."name" ILIKE '%FRANKLIN LIZIMACO %' )
OR (prison_person.last_name ILIKE '%VILLALBA GAROFALO%' OR prison_person."name" ILIKE '%DIEGO HERNAN %' )
OR (prison_person.last_name ILIKE '%LOPEZ MENDIETA%' OR prison_person."name" ILIKE '%JHON JAIRO %' )
OR (prison_person.last_name ILIKE '%CONDOR QUINGA%' OR prison_person."name" ILIKE '%LUIS RENE %' )
OR (prison_person.last_name ILIKE '%GAIBOR VARGAS%' OR prison_person."name" ILIKE '%WILSON ORLANDO %' )
OR (prison_person.last_name ILIKE '%SOTOMAYOR MONTERO%' OR prison_person."name" ILIKE '%JAVIER GERMAN %' )
OR (prison_person.last_name ILIKE '%CALDERON%' OR prison_person."name" ILIKE '%JOSE EIMAR %' )
OR (prison_person.last_name ILIKE '%MEJIA OJEDA%' OR prison_person."name" ILIKE '%KLEVER JAVIER %' )
OR (prison_person.last_name ILIKE '%PILALUMBO UMAGINGA%' OR prison_person."name" ILIKE '%LUIS JAVIER %' )
OR (prison_person.last_name ILIKE '%AGUAY ALBAN%' OR prison_person."name" ILIKE '%ANTONIO RENAN %' )
OR (prison_person.last_name ILIKE '%MONTERO ESPINOZA%' OR prison_person."name" ILIKE '%VINICIO ANDRES %' )
OR (prison_person.last_name ILIKE '%ALVARADO SERRANO%' OR prison_person."name" ILIKE '%LUIS MANUEL %' )
OR (prison_person.last_name ILIKE '%CEDEÑO ALCIVAR%' OR prison_person."name" ILIKE '%YANDRY HERIBERTO %' )
OR (prison_person.last_name ILIKE '%ROJAS LUGO%' OR prison_person."name" ILIKE '%JESUS ENRIQUE %' )
OR (prison_person.last_name ILIKE '%ANGULO IBARRA%' OR prison_person."name" ILIKE '%MARCO ANDRES%' )
OR (prison_person.last_name ILIKE '%ARCE MENDEZ%' OR prison_person."name" ILIKE '%WILMER GERARDO %' )
OR (prison_person.last_name ILIKE '%MARTINEZ UREÑA%' OR prison_person."name" ILIKE '%JAVIER%' )
OR (prison_person.last_name ILIKE '%SUAREZ TORRES%' OR prison_person."name" ILIKE '%JERSSON CAMILO %' )
OR (prison_person.last_name ILIKE '%BANCHON MANZABA%' OR prison_person."name" ILIKE '%LUIS ALFREDO%' )
OR (prison_person.last_name ILIKE '%ORTIZ QUINTANA%' OR prison_person."name" ILIKE '%ERWIN ISRAEL%' )
OR (prison_person.last_name ILIKE '%BOLAÑOS GUANCHA%' OR prison_person."name" ILIKE '%DIEGO EDUARDO %' )
OR (prison_person.last_name ILIKE '%CANACUAN TARAPUEZ%' OR prison_person."name" ILIKE '%LUIS GUSTAVO %' )
OR (prison_person.last_name ILIKE '%GUANCHA ROSERO%' OR prison_person."name" ILIKE '%EDGAR ALEXANDER%' )
OR (prison_person.last_name ILIKE '%JARAMILLO MENA%' OR prison_person."name" ILIKE '%EDWIN IVAN %' )
OR (prison_person.last_name ILIKE '%GUTIERREZ ROJAS%' OR prison_person."name" ILIKE '%GERMAN ANDRES %' )
OR (prison_person.last_name ILIKE '%JEREZ SERPA%' OR prison_person."name" ILIKE '%WILLIAM ROBERTO %' )
OR (prison_person.last_name ILIKE '%HURTADO VERA%' OR prison_person."name" ILIKE '%JUAN IGNACIO %' )
OR (prison_person.last_name ILIKE '%VALVERDE GUALPA%' OR prison_person."name" ILIKE '%EDISON FRANKLIN%' )
OR (prison_person.last_name ILIKE '%MERA HOLGUIN%' OR prison_person."name" ILIKE '%JOSE LUIS %' )
OR (prison_person.last_name ILIKE '%QUIÑONEZ DE LEON%' OR prison_person."name" ILIKE '%LUIS ANISAL %' )
OR (prison_person.last_name ILIKE '%MANOBANDA PULIG%' OR prison_person."name" ILIKE '%FRANKLIN JONATHAN %' )
OR (prison_person.last_name ILIKE '%ARBOLEDA BENAVIDES%' OR prison_person."name" ILIKE '%CHRISTIAN ANDRES%' )
OR (prison_person.last_name ILIKE '%QUIÑONEZ RAMIREZ%' OR prison_person."name" ILIKE '%JOSE LUIS %' )
OR (prison_person.last_name ILIKE '%TORREGROSA MORALES%' OR prison_person."name" ILIKE '%BREYNER ARMANDO%' )
OR (prison_person.last_name ILIKE '%DIAZ CORTES%' OR prison_person."name" ILIKE '%JUAN CARLOS %' )
OR (prison_person.last_name ILIKE '%CARO VALLE%' OR prison_person."name" ILIKE '%FERNANDO JHOEL%' )
OR (prison_person.last_name ILIKE '%MORALES OSANDO%' OR prison_person."name" ILIKE '%HEYBER %' )
OR (prison_person.last_name ILIKE '%CALED PILALONGA%' OR prison_person."name" ILIKE '%ANDRES%' )
OR (prison_person.last_name ILIKE '%GONZALEZ GOITIA%' OR prison_person."name" ILIKE '%ARVIC ALFONSO %' )
OR (prison_person.last_name ILIKE '%CASTRO BURGOS%' OR prison_person."name" ILIKE '%LEONARDO LENIN%' )
OR (prison_person.last_name ILIKE '%GARCIA SUAREZ%' OR prison_person."name" ILIKE '%JOSE LUIS%' )
OR (prison_person.last_name ILIKE '%COLOMA QUINAPAXI%' OR prison_person."name" ILIKE '%LUIS RAUL%' )
OR (prison_person.last_name ILIKE '%BARRES GOLLE%' OR prison_person."name" ILIKE '%JOSE LUIS%' )
OR (prison_person.last_name ILIKE '%CAZAR GONZAGA%' OR prison_person."name" ILIKE '%FRANKLIN ESTEBAN%' )
OR (prison_person.last_name ILIKE '%CHANGUAN FERNANDEZ%' OR prison_person."name" ILIKE '%MANUEL MESIAS%' )
OR (prison_person.last_name ILIKE '%CONDOR AGUILAR%' OR prison_person."name" ILIKE '%CARLOS MARCELO%' )
OR (prison_person.last_name ILIKE '%CUASCOTA SUAREZ%' OR prison_person."name" ILIKE '%SEGUNDO ISRAEL%' )
OR (prison_person.last_name ILIKE '%FALCONI HIDALGO%' OR prison_person."name" ILIKE '%OSCAR ARTURO%' )
OR (prison_person.last_name ILIKE '%LEONES QUINTERO%' OR prison_person."name" ILIKE '%JOVANNY XAVIER%' )
OR (prison_person.last_name ILIKE '%MOLINA RUIZ%' OR prison_person."name" ILIKE '%BORIS EDUARDO%' )
OR (prison_person.last_name ILIKE '%NUÑEZ PESANTEZ%' OR prison_person."name" ILIKE '%DANIEL LEONARDO%' )
OR (prison_person.last_name ILIKE '%VASQUEZ MORALES%' OR prison_person."name" ILIKE '%FRANCISCO ALBERTO%' )
OR (prison_person.last_name ILIKE '%VILLA ORTIZ%' OR prison_person."name" ILIKE '%DEIBY ARMANDO%' )
OR (prison_person.last_name ILIKE '%RODRIGUEZ%' OR prison_person."name" ILIKE '%GUSTAVO RAMIRO%' )
OR (prison_person.last_name ILIKE '%PINCHOPA NANTIP%' OR prison_person."name" ILIKE '%FRANKLIN JULIO%' )
OR (prison_person.last_name ILIKE '%BENAVIDES CONSTAIN%' OR prison_person."name" ILIKE '%ARTURO EFRAIN%' )
OR (prison_person.last_name ILIKE '%GOMEZ MOREIRA%' OR prison_person."name" ILIKE '%TEOFILO LAUTARO%' )
OR (prison_person.last_name ILIKE '%OLVERA SEGURA%' OR prison_person."name" ILIKE '%PATRICIO LEONARDO%' )
OR (prison_person.last_name ILIKE '%TUNJA CEDEÑO%' OR prison_person."name" ILIKE '%FRIXON GUSTAVO%' )
OR (prison_person.last_name ILIKE '%GARCES CEDEÑO%' OR prison_person."name" ILIKE '%JACINTO AGUSTIN%' )
OR (prison_person.last_name ILIKE '%CARREÑO QUIÑONEZ%' OR prison_person."name" ILIKE '%EPIFANIO LEODAN%' )
OR (prison_person.last_name ILIKE '%CASIERRA CAIDEDO%' OR prison_person."name" ILIKE '%LUIS ALBERTO%' )
OR (prison_person.last_name ILIKE '%MINA QUINTEROS%' OR prison_person."name" ILIKE '%EDISON LUIS%' )
OR (prison_person.last_name ILIKE '%PIEDRA MOROCHO%' OR prison_person."name" ILIKE '%DANNY DANIEL%' )
OR (prison_person.last_name ILIKE '%SOLORZANO BARRE%' OR prison_person."name" ILIKE '%OSCAR MANUEL%' )
OR (prison_person.last_name ILIKE '%FILIAN CRUZ%' OR prison_person."name" ILIKE '%PABLO ENRIQUE%' )
OR (prison_person.last_name ILIKE '%PEREA HURTADO%' OR prison_person."name" ILIKE '%JANNER IVAN%' )
OR (prison_person.last_name ILIKE '%SOSA SOSA%' OR prison_person."name" ILIKE '%BYRON BLADIMIR%' )
OR (prison_person.last_name ILIKE '%PERALVO ROMERO%' OR prison_person."name" ILIKE '%LUIS JAVIER%' )
OR (prison_person.last_name ILIKE '%MONTAÑO COLOBON%' OR prison_person."name" ILIKE '%HECTOR ALFREDO%' )
OR (prison_person.last_name ILIKE '%CEDEÑO BARRE%' OR prison_person."name" ILIKE '%GALO WILMER%' )
OR (prison_person.last_name ILIKE '%LLININ YUCTA%' OR prison_person."name" ILIKE '%MARCO FABIAN%' )
OR (prison_person.last_name ILIKE '%MINOTA QUIÑONEZ%' OR prison_person."name" ILIKE '%ALEXIS GASPAR%' )
OR (prison_person.last_name ILIKE '%GUANOLUISA ALMACHE%' OR prison_person."name" ILIKE '%GALO EDUARDO%' )
OR (prison_person.last_name ILIKE '%CORTEZ CORTEZ%' OR prison_person."name" ILIKE '%JHONNY FERNANDO%' )
OR (prison_person.last_name ILIKE '%CALAHORRANO QUEVEDO%' OR prison_person."name" ILIKE '%CARLOS ALFREDO%' )
OR (prison_person.last_name ILIKE '%CERVANTES PERALTA%' OR prison_person."name" ILIKE '%JORGE ENRIQUE%' )
OR (prison_person.last_name ILIKE '%CHAVEZ PANTOJA%' OR prison_person."name" ILIKE '%OSCAR ALEJANDRO%' )
OR (prison_person.last_name ILIKE '%CHOEZ CHOEZ%' OR prison_person."name" ILIKE '%ANGEL JOEL%' )
OR (prison_person.last_name ILIKE '%CORNEJO ANCHUNDIA%' OR prison_person."name" ILIKE '%EDWIN ARISTIDES%' )
OR (prison_person.last_name ILIKE '%ORTIZ VALENCIA%' OR prison_person."name" ILIKE '%CARLOS ALBERTO%' )
OR (prison_person.last_name ILIKE '%PEÑA ABAD%' OR prison_person."name" ILIKE '%WILMER ROSBYLL%' )
OR (prison_person.last_name ILIKE '%URETA DELGADO%' OR prison_person."name" ILIKE '%FREDDY LORENSO%' )
OR (prison_person.last_name ILIKE '%ZAMBRANO TARAZONA%' OR prison_person."name" ILIKE '%JAIRO EUGENIO%' )
OR (prison_person.last_name ILIKE '%ZAMBRANO ZAMORA%' OR prison_person."name" ILIKE '%RAMON ANTONIO%' )
OR (prison_person.last_name ILIKE '%MORENO BUSTOS%' OR prison_person."name" ILIKE '%JOSE LUIS%' )
OR (prison_person.last_name ILIKE '%ZAMBRANO TARAZONA%' OR prison_person."name" ILIKE '%JAIRO EUGENIO %' )
OR (prison_person.last_name ILIKE '%ZAMBRANO ZAMORA%' OR prison_person."name" ILIKE '%RAMON ANTONIO%' )
OR (prison_person.last_name ILIKE '%MORENO BUSTOS%' OR prison_person."name" ILIKE '%JOSE LUIS %' )
OR (prison_person.last_name ILIKE '%CORDOVA CARVAJAL%' OR prison_person."name" ILIKE '%DANNY MANUEL %' )
OR (prison_person.last_name ILIKE '%JURADO RAMIREZ%' OR prison_person."name" ILIKE '%MARIO ENRIQUE %' )
OR (prison_person.last_name ILIKE '%GUANOQUIZA  NINASUNTA%' OR prison_person."name" ILIKE '%DANIEL ARDUINO%' )
OR (prison_person.last_name ILIKE '%BERMELLO CHANG%' OR prison_person."name" ILIKE '%CRISTIAN  DANIEL %' )
OR (prison_person.last_name ILIKE '%ZAGAL VEGA%' OR prison_person."name" ILIKE '%JOSE IVAN %' )
OR (prison_person.last_name ILIKE '%HENAO HURTADO%' OR prison_person."name" ILIKE '%BLEYMAN ENRIQUE%' )
OR (prison_person.last_name ILIKE '%CHAVEZ LOZA%' OR prison_person."name" ILIKE '%DIOGENES RAMON%' )
OR (prison_person.last_name ILIKE '%SANCHEZ SEGURA%' OR prison_person."name" ILIKE '%JOSE ELIAS %' )
OR (prison_person.last_name ILIKE '%SOLORZANO VERA%' OR prison_person."name" ILIKE '%RAMON ROBERTO%' )
OR (prison_person.last_name ILIKE '%VEGA GARCIA%' OR prison_person."name" ILIKE '%MATEO NIGOLAS %' )
OR (prison_person.last_name ILIKE '%ALBAN PEREZ%' OR prison_person."name" ILIKE '%BRYANT JHONATHAN%' )
OR (prison_person.last_name ILIKE '%CORTEZ PRECIADO%' OR prison_person."name" ILIKE '%PATROCINIO%' )
OR (prison_person.last_name ILIKE '%LLIVIGAÑAY IÑIGUEZ%' OR prison_person."name" ILIKE '%DAVID LEONARDO %' )
OR (prison_person.last_name ILIKE '%CERDA YUMBO%' OR prison_person."name" ILIKE '%JAIME RAFAEL %' )
OR (prison_person.last_name ILIKE '%POMA AGUALONGO%' OR prison_person."name" ILIKE '%HENRY RUPERTO%' )
OR (prison_person.last_name ILIKE '%AYENLA TENORIO%' OR prison_person."name" ILIKE '%ORLANDO JAVIER %' )
OR (prison_person.last_name ILIKE '%CHANCAY CHOEZ%' OR prison_person."name" ILIKE '%WALTER EDISON%' )
OR (prison_person.last_name ILIKE '%TENELEMA CHISAGUANO%' OR prison_person."name" ILIKE '% EDISON PATRICIO%' )
OR (prison_person.last_name ILIKE '%UMAJINGA CANDELEJO%' OR prison_person."name" ILIKE '%KLEVER FRANKLIN%' )
OR (prison_person.last_name ILIKE '%MARTINEZ ARBOLEDA%' OR prison_person."name" ILIKE '%LUIS ROBERTO%' )
OR (prison_person.last_name ILIKE '%MORALES VELEZ%' OR prison_person."name" ILIKE '%VICENTE XAVIER %' )
OR (prison_person.last_name ILIKE '%MOSQUERA KLINGER%' OR prison_person."name" ILIKE '%WILLINGTON  ELIAS%' )
OR (prison_person.last_name ILIKE '%MALLA VILLARES%' OR prison_person."name" ILIKE '%ROBERTO RODOLFO %' )
OR (prison_person.last_name ILIKE '%TELLO CORDOVA%' OR prison_person."name" ILIKE '%JUAN DAGOBERTO  %' )
OR (prison_person.last_name ILIKE '%CAJAMARCA FLORES%' OR prison_person."name" ILIKE '%ERIK SAMUEL %' )
OR (prison_person.last_name ILIKE '%ANGULO QUINTERO%' OR prison_person."name" ILIKE '%JAIRO JAVIER %' )
OR (prison_person.last_name ILIKE '%MONTAÑO QUINTERO%' OR prison_person."name" ILIKE '%FREDIS DANIEL%' )
OR (prison_person.last_name ILIKE '%SEGURA ARROYO%' OR prison_person."name" ILIKE '%DARWIN SEGUNDO%' )
OR (prison_person.last_name ILIKE '%REASCO RUIZ%' OR prison_person."name" ILIKE '%RITO JAYRO%' )
OR (prison_person.last_name ILIKE '%DUARTE PAZMIÑO%' OR prison_person."name" ILIKE '%ANDERSON JAIR%' )
OR (prison_person.last_name ILIKE '%SEGURA RIVERA%' OR prison_person."name" ILIKE '%SILVIO JAVIER%' )
OR (prison_person.last_name ILIKE '%ZAMORA MACIAS%' OR prison_person."name" ILIKE '%JAVIER EUDALDO%' )
OR (prison_person.last_name ILIKE '%MAYO CEDEÑO%' OR prison_person."name" ILIKE '%EDISON PATRICIO%' )
OR (prison_person.last_name ILIKE '%MEZA CAMPOS%' OR prison_person."name" ILIKE '%CRISTIAN EDUARDO%' )
OR (prison_person.last_name ILIKE '%SAMIK COCHINCHA%' OR prison_person."name" ILIKE '%LUIS NELSON%' )
OR (prison_person.last_name ILIKE '%CLAVIJO DEL CASTILLO%' OR prison_person."name" ILIKE '%CARLOS ALBERTO%' )
OR (prison_person.last_name ILIKE '%BANGUERA INTRIAGO%' OR prison_person."name" ILIKE '%ISAIAS ISMAEL%' )
OR (prison_person.last_name ILIKE '%AVILA TRIVIÑO%' OR prison_person."name" ILIKE '%DARWIN ISRAEL%' )
OR (prison_person.last_name ILIKE '%CRUZ AMAGUAÑA%' OR prison_person."name" ILIKE '%BRYAN ALEJANDRO%' )
OR (prison_person.last_name ILIKE '%NARANJO JACHO%' OR prison_person."name" ILIKE '%JONATHAN JAVIER%' )
OR (prison_person.last_name ILIKE '%CARDENAS RIVERA%' OR prison_person."name" ILIKE '%JEFFERSON FERNANDO%' )
OR (prison_person.last_name ILIKE '%VALLEJO PESANTE%' OR prison_person."name" ILIKE '%BORIS EDISON%' )
OR (prison_person.last_name ILIKE '%VERA GUERRERO%' OR prison_person."name" ILIKE '%FERNANDO HERIBERTO%' )
OR (prison_person.last_name ILIKE '%AGUIRRE BENAVIDES%' OR prison_person."name" ILIKE '%MIGUEL ADOLFO%' )
OR (prison_person.last_name ILIKE '%BECERRA HENAO%' OR prison_person."name" ILIKE '%CRISTIAN FERNANDO%' )
OR (prison_person.last_name ILIKE '%CAMACHO PACHECO%' OR prison_person."name" ILIKE '%TERRY ISRAEL%' )
OR (prison_person.last_name ILIKE '%CHILA MINA%' OR prison_person."name" ILIKE '%JOSE MANUEL%' )
OR (prison_person.last_name ILIKE '%ARROYO PRECIADO%' OR prison_person."name" ILIKE '%JOSE JHAIR%' )
OR (prison_person.last_name ILIKE '%ARCE CHICHANDE%' OR prison_person."name" ILIKE '%WILMAR JAVIER%' )
OR (prison_person.last_name ILIKE '%ESPINOZA LASTRE%' OR prison_person."name" ILIKE '%SERGIO REINER%' )
OR (prison_person.last_name ILIKE '%LAMINGO MORENO%' OR prison_person."name" ILIKE '%EDSON JAIR%' )
OR (prison_person.last_name ILIKE '%SANGACHA INCA%' OR prison_person."name" ILIKE '%MIGUEL ANGEL%' )
OR (prison_person.last_name ILIKE '%GUERRERO RIASCOS%' OR prison_person."name" ILIKE '%WILSON FERNEY%' )
OR (prison_person.last_name ILIKE '%ORTEGA TARAPUES%' OR prison_person."name" ILIKE '%DARIO JAVIER%' )
OR (prison_person.last_name ILIKE '%RIVERA GARCIA%' OR prison_person."name" ILIKE '%ROLAND STALYN%' )
OR (prison_person.last_name ILIKE '%ROMERO TOLEDO%' OR prison_person."name" ILIKE '%JORGE LUIS%' )
OR (prison_person.last_name ILIKE '%JAMA LOZANO%' OR prison_person."name" ILIKE '%MANUEL ADOLFO%' )
OR (prison_person.last_name ILIKE '%LOMBEIDA ROSERO%' OR prison_person."name" ILIKE '%MICHAEL ANDRES%' )
OR (prison_person.last_name ILIKE '%CALVACHE SALAZAR%' OR prison_person."name" ILIKE '%ANGEL ARTURO%' )
OR (prison_person.last_name ILIKE '%GUARANDA VELASQUEZ%' OR prison_person."name" ILIKE '%JOSE DAVID%' )
OR (prison_person.last_name ILIKE '%LOZANO DONOSO%' OR prison_person."name" ILIKE '%LUIS ALBERTO%' )
OR (prison_person.last_name ILIKE '%PABON HERNANDEZ%' OR prison_person."name" ILIKE '% CARLOS AUGUSTO%' )
OR (prison_person.last_name ILIKE '%CORTEZ PEREZ%' OR prison_person."name" ILIKE '%JOSE MIGUEL%' )
OR (prison_person.last_name ILIKE '%CUASTUMAL CUASTUMAL%' OR prison_person."name" ILIKE '%JUSTO SEGUNDO%' )
OR (prison_person.last_name ILIKE '%ESPINOZA CARCELEN%' OR prison_person."name" ILIKE '%JHONY ESTUARDO%' )
OR (prison_person.last_name ILIKE '%VALVERDE SIFUENTES%' OR prison_person."name" ILIKE '%BRAULIO RUBEN%' )
OR (prison_person.last_name ILIKE '%CUNALATA GAVILANEZ%' OR prison_person."name" ILIKE '%JORGE ARMANDO%' )
OR (prison_person.last_name ILIKE '%CORDOVA CELI%' OR prison_person."name" ILIKE '%JULIO MAURICIO%' )
OR (prison_person.last_name ILIKE '%RENGIFO DE LA TORRE%' OR prison_person."name" ILIKE '%DAVID EDUARDO%' )
OR (prison_person.last_name ILIKE '%VICENTE ESTACIO%' OR prison_person."name" ILIKE '%JHON ALEXANDER%' )
OR (prison_person.last_name ILIKE '%RODRIGUEZ ZAMBRANO%' OR prison_person."name" ILIKE '%EDISON FABIAN%' )
OR (prison_person.last_name ILIKE '% LANDAZURI CAICEDO%' OR prison_person."name" ILIKE '%WELLINGTON GALO%' )
OR (prison_person.last_name ILIKE '%QUIÑONEZ CRIOLLO%' OR prison_person."name" ILIKE '%ANDRES ARTURO%' )
OR (prison_person.last_name ILIKE '%MARIN RAMIREZ%' OR prison_person."name" ILIKE '%YHONY ANDRES%' )
OR (prison_person.last_name ILIKE '%CASIERRA CORTEZ%' OR prison_person."name" ILIKE '%PABLO DAVID%' )
OR (prison_person.last_name ILIKE '%JAMA GONZALES%' OR prison_person."name" ILIKE '%MANUEL EFREN%' )
OR (prison_person.last_name ILIKE '%MEDRANDA QUIROZ%' OR prison_person."name" ILIKE '%EDISON SEBASTIAN%' )
OR (prison_person.last_name ILIKE '%BUITRON MORALES%' OR prison_person."name" ILIKE '%IVAN EDUARDO%' )
OR (prison_person.last_name ILIKE '%GOMEZ ALVAREZ%' OR prison_person."name" ILIKE '%JUVER RICARDO%' )
OR (prison_person.last_name ILIKE '%MENSIAS SALAZAR%' OR prison_person."name" ILIKE '%PEDRO PABLO%' )
OR (prison_person.last_name ILIKE '%OBANDO SALAZAR%' OR prison_person."name" ILIKE '%CRISTHIAN STALIN%' )
OR (prison_person.last_name ILIKE '%SALAZAR AYALA%' OR prison_person."name" ILIKE '%ARTURO JAVIER%' )
OR (prison_person.last_name ILIKE '%SANGUCHO CHICAIZA%' OR prison_person."name" ILIKE '%SANTIAGO FERNANDO%' )
OR (prison_person.last_name ILIKE '%TORRES ESTACIO%' OR prison_person."name" ILIKE '%LUIS HERNAN%' )
OR (prison_person.last_name ILIKE '%PARRALES SORIANO%' OR prison_person."name" ILIKE '%TONNY MANUEL%' )
OR (prison_person.last_name ILIKE '%VALVERDE MEDINA%' OR prison_person."name" ILIKE '%FRANKLIN RAUL%' )
OR (prison_person.last_name ILIKE '% GUALOTUÑA ALQUINGA%' OR prison_person."name" ILIKE '%EDWIN XAVIER%' )
OR (prison_person.last_name ILIKE '%REMACHE TIPANQUIZA%' OR prison_person."name" ILIKE '% FREDDY ISRAEL%' )
OR (prison_person.last_name ILIKE '%CUEVA MOLINA%' OR prison_person."name" ILIKE '%LUIS AMADO%' )
OR (prison_person.last_name ILIKE '%MERINO TARQUI%' OR prison_person."name" ILIKE '%HENRY GERMAN%' )
OR (prison_person.last_name ILIKE '%VILLEGAS PANEZO%' OR prison_person."name" ILIKE '%JUNIOR MIGUEL%' )
OR (prison_person.last_name ILIKE '%ALARCON COS%' OR prison_person."name" ILIKE '%MANUEL URBANO%' )
OR (prison_person.last_name ILIKE '%BENITEZ VELESACA%' OR prison_person."name" ILIKE '%JONATHAN STEEVEN%' )
OR (prison_person.last_name ILIKE '%FLORES MANZABA%' OR prison_person."name" ILIKE '%SERGIO DAVID%' )
OR (prison_person.last_name ILIKE '%GONZALEZ ANGULO%' OR prison_person."name" ILIKE '%ORLINDO LIBORIO%' )
OR (prison_person.last_name ILIKE '%LOPEZ CHAMBA%' OR prison_person."name" ILIKE '%FRANKLIN RIGOBERTO%' )
OR (prison_person.last_name ILIKE '%LOPEZ TORO%' OR prison_person."name" ILIKE '%DARWIN DANIEL%' )
OR (prison_person.last_name ILIKE '%MATUTE GUEVARA%' OR prison_person."name" ILIKE '%BYRON DE JESUS%' )
OR (prison_person.last_name ILIKE '%MURILLO VELEZ%' OR prison_person."name" ILIKE '%WALTER JOEL%' )
OR (prison_person.last_name ILIKE '%ORDOÑEZ OCAMPO%' OR prison_person."name" ILIKE '%DARWIN FERNANDO%' )
OR (prison_person.last_name ILIKE '%ORELLANA SUAREZ%' OR prison_person."name" ILIKE '%RODOLFO ALEJANDRO%' )
OR (prison_person.last_name ILIKE '%ORTIZ MENDOZA%' OR prison_person."name" ILIKE '%JULIO CESAR%' )
OR (prison_person.last_name ILIKE '%ORTIZ RODRIGUEZ%' OR prison_person."name" ILIKE '%ELIECER ORLEY%' )
OR (prison_person.last_name ILIKE '%VIÑAN SACON%' OR prison_person."name" ILIKE '%CARLOS DANILO%' )
OR (prison_person.last_name ILIKE '%TULCANAZA IMBAQUINGO%' OR prison_person."name" ILIKE '%GALO MAURICIO%' )
OR (prison_person.last_name ILIKE '%TUQUERREZ IPIALES%' OR prison_person."name" ILIKE '%VICTOR MANUEL%' )
OR (prison_person.last_name ILIKE '%LUNA CASTILLO%' OR prison_person."name" ILIKE '%NEY DE JESUS%' )
OR (prison_person.last_name ILIKE '%MENDOZA FARINANGO%' OR prison_person."name" ILIKE '%SEGUNDO%' )
OR (prison_person.last_name ILIKE '%GARCIA BAIRON%' OR prison_person."name" ILIKE '%ALEXANDER%' )
OR (prison_person.last_name ILIKE '%CARVAJAL HEREDIA%' OR prison_person."name" ILIKE '%MARIO ESTEBAN%' )
OR (prison_person.last_name ILIKE '%GAGUANCELA MAROTO%' OR prison_person."name" ILIKE '%CHRISTIAN FERNANDO%' )
OR (prison_person.last_name ILIKE '%GUAMAN MUENALA%' OR prison_person."name" ILIKE '%LUIS ALONSO%' )
OR (prison_person.last_name ILIKE '%ALENCASTRO LAGLA%' OR prison_person."name" ILIKE '%EDISON RICARDO%' )
OR (prison_person.last_name ILIKE '%ALUCHO QUINALOA%' OR prison_person."name" ILIKE '%ELIAS PEDRO%' )
OR (prison_person.last_name ILIKE '%BELTRAN%' OR prison_person."name" ILIKE '%MIGUEL ANGEL%' )
OR (prison_person.last_name ILIKE '%ZAPATA CORTES%' OR prison_person."name" ILIKE '%JOSE EDISON%' )
OR (prison_person.last_name ILIKE '%CARRILLO SANCHEZ%' OR prison_person."name" ILIKE '%RONMEL ALEJANDRO%' )
OR (prison_person.last_name ILIKE '%LANDETA ULCUANGO%' OR prison_person."name" ILIKE '%CARLOS OCTAVIO%' )
OR (prison_person.last_name ILIKE '%AZA VALENCIA%' OR prison_person."name" ILIKE '%JORGE ANTONIO%' )
OR (prison_person.last_name ILIKE '%GUEVARA PICO%' OR prison_person."name" ILIKE '%JUAN FRANCISCO%' )
OR (prison_person.last_name ILIKE '%DIAZ PAUCAR%' OR prison_person."name" ILIKE '%SEGUNDO MANUEL%' )
OR (prison_person.last_name ILIKE '%VALENCIA REINOSO%' OR prison_person."name" ILIKE '%JUAN CARLOS%' )
OR (prison_person.last_name ILIKE '%CHAMBA CHAMBA%' OR prison_person."name" ILIKE '%LUIS CARLOS%' )
OR (prison_person.last_name ILIKE '%CARRANZA MUÑOZ%' OR prison_person."name" ILIKE '%LUIS ENRIQUE%' )
OR (prison_person.last_name ILIKE '%CUSQUILLO PEREZ%' OR prison_person."name" ILIKE '%JOSE ENRIQUE%' )
OR (prison_person.last_name ILIKE '%ULLAH%' OR prison_person."name" ILIKE '%KIFAYAT%' )
OR (prison_person.last_name ILIKE '%NEIRA SATIZABAL%' OR prison_person."name" ILIKE '%JUAN CAMILO%' )
OR (prison_person.last_name ILIKE '%DIAZ QUINONEZ%' OR prison_person."name" ILIKE '%DIEGO DUVAN%' )
OR (prison_person.last_name ILIKE '%HERNANDEZ GARCIA%' OR prison_person."name" ILIKE '%MIGUEL ANGEL%' )
OR (prison_person.last_name ILIKE '%MORA SOLIS%' OR prison_person."name" ILIKE '%ANGEL MIGUEL%' )
OR (prison_person.last_name ILIKE '%PILCA CAIZA%' OR prison_person."name" ILIKE '%ANDY JUAN%' )
OR (prison_person.last_name ILIKE '%MURILLO ANDRADE%' OR prison_person."name" ILIKE '%RAUL DWAN%' )
OR (prison_person.last_name ILIKE '%BASURTO MACIAS%' OR prison_person."name" ILIKE '%LUIS GEOVANNY%' )
OR (prison_person.last_name ILIKE '%CUERO QUIÑONEZ%' OR prison_person."name" ILIKE '%FRANCLIN MANUEL%' )
OR (prison_person.last_name ILIKE '%SAA BELTRAN%' OR prison_person."name" ILIKE '%LUIS ALFREDO%' )
OR (prison_person.last_name ILIKE '%GUERRERO MORALES%' OR prison_person."name" ILIKE '%RAMIRO WLADIMIR%' )
OR (prison_person.last_name ILIKE '%ROMOLEROUX MOSCOSO%' OR prison_person."name" ILIKE '%DIEGO PAUL%' )
OR (prison_person.last_name ILIKE '%TABORDA CASTAÑEDA%' OR prison_person."name" ILIKE '%JUAN DIEGO%' )
OR (prison_person.last_name ILIKE '%COROZO ARROYO%' OR prison_person."name" ILIKE '%STALIN DAREL%' )
OR (prison_person.last_name ILIKE '%MORALES RUALES%' OR prison_person."name" ILIKE '%NORBEY FERNANDO%' )
OR (prison_person.last_name ILIKE '%ARCE ARCE%' OR prison_person."name" ILIKE '%PABLO RIGOBERTO%' )
OR (prison_person.last_name ILIKE '%MONTENEGRO%' OR prison_person."name" ILIKE '%PALAFOX HUGO OMAR%' )
OR (prison_person.last_name ILIKE '%MUZO MUÑOZ%' OR prison_person."name" ILIKE '%DIEGO MAURICIO%' )
OR (prison_person.last_name ILIKE '%VARGAS CAPA%' OR prison_person."name" ILIKE '%HECTOR MANUEL%' )
OR (prison_person.last_name ILIKE '%LOZANO TARIS%' OR prison_person."name" ILIKE '%DARIO JAVIER%' )
OR (prison_person.last_name ILIKE '%BARREIRO ALCIVAR%' OR prison_person."name" ILIKE '%JEFFERSON LEONEL%' )
OR (prison_person.last_name ILIKE '%CANACUAN GUERRERO%' OR prison_person."name" ILIKE '%LUIS ALFONSO%' )
OR (prison_person.last_name ILIKE '%CORTEZ RAYO%' OR prison_person."name" ILIKE '%LUIS ANTONIO%' )
OR (prison_person.last_name ILIKE '%FIGUEROA MERA%' OR prison_person."name" ILIKE '%JHON JULIAN%' )
OR (prison_person.last_name ILIKE '%MOYANO CONTRERAS%' OR prison_person."name" ILIKE '%RONALD JONATHAN%' )
OR (prison_person.last_name ILIKE '%SANCHEZ VARON%' OR prison_person."name" ILIKE '%HERNANDO%' )
OR (prison_person.last_name ILIKE '%LONDOÑO FERRIN%' OR prison_person."name" ILIKE '%WHILMER ANTONIO%' )
OR (prison_person.last_name ILIKE '%ROMAN RODRIGUEZ%' OR prison_person."name" ILIKE '%WILMER ADRIAN%' )
OR (prison_person.last_name ILIKE '%ANGULO LARA%' OR prison_person."name" ILIKE '%CARLOS EDWIN%' )
OR (prison_person.last_name ILIKE '%ORTEGA CAICEDO%' OR prison_person."name" ILIKE '%SEGUNDO LEYNER%' )
OR (prison_person.last_name ILIKE '%VALDEZ REYES%' OR prison_person."name" ILIKE '%JERARDO%' )
OR (prison_person.last_name ILIKE '%BARRERA CAISA%' OR prison_person."name" ILIKE '%JONATHAN EMANUEL%' )
OR (prison_person.last_name ILIKE '%PINTO CRIOLLO%' OR prison_person."name" ILIKE '%JUAN PABLO%' )
OR (prison_person.last_name ILIKE '%MENDEZ CORTEZ%' OR prison_person."name" ILIKE '%CARLOS ALFREDO%' )
OR (prison_person.last_name ILIKE '%PEREIRA ANGULO%' OR prison_person."name" ILIKE '%ANDRES%' )
OR (prison_person.last_name ILIKE '%PEREZ VILLAMARIN%' OR prison_person."name" ILIKE '%GEOVANNY AQUILES%' )
OR (prison_person.last_name ILIKE '%LAMAR TRUJILLO%' OR prison_person."name" ILIKE '%ANGEL VLADIMIR%' )
OR (prison_person.last_name ILIKE '%CHALAN MORALES%' OR prison_person."name" ILIKE '%SEGUNDO AMADOR%' )
OR (prison_person.last_name ILIKE '%GUAMAN GUAMAN%' OR prison_person."name" ILIKE '%SEGUNDO WLAOIMIR%' )
OR (prison_person.last_name ILIKE '%LLIVISACA ORELLANA%' OR prison_person."name" ILIKE '%LUIS FERNANDO%' )
OR (prison_person.last_name ILIKE '%PANCHI CEVALLOS%' OR prison_person."name" ILIKE '%EDWIN PATRICIO%' )
OR (prison_person.last_name ILIKE '%MINA CHILLAMBO%' OR prison_person."name" ILIKE '%ROJERES JOHER%' )
OR (prison_person.last_name ILIKE '%CASTILLO GUACHIZACA%' OR prison_person."name" ILIKE '%JHANDRY XAVIER%' )
OR (prison_person.last_name ILIKE '%CHATO YUGSI%' OR prison_person."name" ILIKE '%HUGO BAYARDO%' )
OR (prison_person.last_name ILIKE '%OÑA YUGSI%' OR prison_person."name" ILIKE '%ROBERTO WLADIMIR%' )
OR (prison_person.last_name ILIKE '%PINAGORTE GUASHAMBO%' OR prison_person."name" ILIKE '%OSWALDO%' )
OR (prison_person.last_name ILIKE '%REMACHE TERAN%' OR prison_person."name" ILIKE '%EDWIN OMAR%' )
OR (prison_person.last_name ILIKE '%LONDOÑO ALBAN%' OR prison_person."name" ILIKE '%WALTER STEVEN%' )
OR (prison_person.last_name ILIKE '%RAMIREZ%' OR prison_person."name" ILIKE '%CARLOS JULIO%' )
OR (prison_person.last_name ILIKE '%WACHAPA USHPA%' OR prison_person."name" ILIKE '%ANGEL PATRICIO%' )
OR (prison_person.last_name ILIKE '%YASACAMA ARANDA%' OR prison_person."name" ILIKE '%DAVID IVAN%' )
OR (prison_person.last_name ILIKE '%CAICEDO HOLGUIN%' OR prison_person."name" ILIKE '%TITO GLUBIS%' )
OR (prison_person.last_name ILIKE '%LEON CARPIO%' OR prison_person."name" ILIKE '%MARCO ANTONIO%' )
OR (prison_person.last_name ILIKE '%PACHECO MARTINEZ%' OR prison_person."name" ILIKE '%BAYRON ANDRES%' )
OR (prison_person.last_name ILIKE '%TIGRERO MARTINEZ%' OR prison_person."name" ILIKE '%JEARSINIO BAUTISTA%' )
OR (prison_person.last_name ILIKE '%QUINONEZ DE LEON%' OR prison_person."name" ILIKE '%LUIS ANISAL%' )
OR (prison_person.last_name ILIKE '%QUIÑONEZ GUEVARA%' OR prison_person."name" ILIKE '%FRIXON GEOVANNY%' )
OR (prison_person.last_name ILIKE '%CARDOZO MOGUA%' OR prison_person."name" ILIKE '%LUIS ANGEL%' )
OR (prison_person.last_name ILIKE '%AMORES SANGUCHO%' OR prison_person."name" ILIKE '%BRYAN STEVE%' )
OR (prison_person.last_name ILIKE '%UNAUCHO CHANALUISA%' OR prison_person."name" ILIKE '%NESTOR DAVID%' )
OR (prison_person.last_name ILIKE '%QUISILEMA TOPON%' OR prison_person."name" ILIKE '%WILMER RENE%' )
OR (prison_person.last_name ILIKE '%MERCADO ECHEVERRIA%' OR prison_person."name" ILIKE '%STALIN ELIAN%' )
OR (prison_person.last_name ILIKE '%BONIFAZ SALAZAR%' OR prison_person."name" ILIKE '%OSCAR ADRIAN%' )
OR (prison_person.last_name ILIKE '%ZURITA USHIÑA%' OR prison_person."name" ILIKE '%PAVEL NICOLAY%' )
OR (prison_person.last_name ILIKE '%PUCACHAQUI LAMINGO%' OR prison_person."name" ILIKE '%CHRISTIAN DAVID%' )
OR (prison_person.last_name ILIKE '%JARAMILLO DOMO%' OR prison_person."name" ILIKE '%EDWIN JAVIER%' )
OR (prison_person.last_name ILIKE '%VARGAS ANGUISACA%' OR prison_person."name" ILIKE '%JOSE RAFAEL%' )
OR (prison_person.last_name ILIKE '%LOOR PONCE%' OR prison_person."name" ILIKE '%LUIS ALBERTO%' )
OR (prison_person.last_name ILIKE '%VASQUEZ TORRES%' OR prison_person."name" ILIKE '%PEDRO PABLO%' )
OR (prison_person.last_name ILIKE '%LEMA SIMALUISA%' OR prison_person."name" ILIKE '%RICARDO DAVID%' )
OR (prison_person.last_name ILIKE '%PIJAL ZULETA%' OR prison_person."name" ILIKE '%RICARDO ANDRES%' )
OR (prison_person.last_name ILIKE '%AGUILAR MORALES%' OR prison_person."name" ILIKE '%ANGEL ESTEBAN%' )
OR (prison_person.last_name ILIKE '%COLLAGUAZO NARVAEZ%' OR prison_person."name" ILIKE '%CARLOS OMAR%' )
OR (prison_person.last_name ILIKE '%PAREDES RODRIGUEZ%' OR prison_person."name" ILIKE '%JIMMY RONMEL%' )
OR (prison_person.last_name ILIKE '%CARRION SANTIANA%' OR prison_person."name" ILIKE '%WILINTON ADRIAN%' )
OR (prison_person.last_name ILIKE '%TOAPANTA TIGSE%' OR prison_person."name" ILIKE '%JONATHAN PATRICIO%' )
OR (prison_person.last_name ILIKE '%ALMACHE SARAVINO%' OR prison_person."name" ILIKE '%ALEX WLADIMIR%' )
OR (prison_person.last_name ILIKE '%RODRIGUEZ MALDONADO%' OR prison_person."name" ILIKE '%ANDRICK MARCELO%' )
ORDER BY 2*/