select * from SIS_EMPRESA empresa,SIS_SUCURSAL sucursal
left join SIS_USUARIO_SUCURSAL usuario_sucursal on USUARIO_SUCURSAL.IDE_SUCU=SUCURSAL.IDE_SUCU
left join SIS_USUARIO usuario on USUARIO.IDE_USUA=USUARIO_SUCURSAL.IDE_USUA
where SUCURSAL.IDE_EMPR=0
and SUCURSAL.IDE_SUCU=1
and USUARIO_SUCURSAL.IDE_USUA=7