WITH RECURSIVE CATALOGO AS ( 
        
SELECT IDE_BOCAM, CON_IDE_BOCAM, CAT_CODIGO_BOCAM, DESCRIPCION_BOCAM, ACTIVO_BOCAM         
FROM BODT_CATALOGO_MATERIAL  WHERE IDE_BOCAM = 2     
UNION ALL         
SELECT E.IDE_BOCAM, E.CON_IDE_BOCAM, E.CAT_CODIGO_BOCAM, E.DESCRIPCION_BOCAM, E.ACTIVO_BOCAM         
FROM BODT_CATALOGO_MATERIAL E         
JOIN CATALOGO ON E.CON_IDE_BOCAM = CATALOGO.IDE_BOCAM

 ) 
 ,  CONTEO_HIJOS AS ( 

	SELECT CATALOGO1.CON_IDE_BOCAM, COUNT(*) AS CANTIDAD_HIJOS FROM CATALOGO  CATALOGO1    GROUP BY 1

 ) 	 

SELECT CATALOGO.IDE_BOCAM, CATALOGO.CAT_CODIGO_BOCAM || ' '  || CATALOGO.DESCRIPCION_BOCAM AS NOMBRE_COMPLETO_MATERIAL, CONTEO_HIJOS.CANTIDAD_HIJOS 
FROM CATALOGO  
LEFT JOIN CONTEO_HIJOS ON CATALOGO.IDE_BOCAM = CONTEO_HIJOS.CON_IDE_BOCAM 
WHERE ACTIVO_BOCAM = TRUE 
AND CONTEO_HIJOS.CANTIDAD_HIJOS IS NULL   
AND  CATALOGO.CON_IDE_BOCAM = '38'