WITH RECURSIVE CATALOGO AS (
   SELECT IDE_BOCAM, CON_IDE_BOCAM, CAT_CODIGO_BOCAM, DESCRIPCION_BOCAM, ACTIVO_BOCAM         
	 FROM BODT_CATALOGO_MATERIAL  WHERE IDE_BOCAM = 2  
   
   UNION ALL         
	SELECT E.IDE_BOCAM, E.CON_IDE_BOCAM, E.CAT_CODIGO_BOCAM, E.DESCRIPCION_BOCAM, E.ACTIVO_BOCAM         
	FROM BODT_CATALOGO_MATERIAL E         
	JOIN CATALOGO ON E.CON_IDE_BOCAM = CATALOGO.IDE_BOCAM
) SELECT * FROM  CATALOGO;